- actions:
  - description: ''
    id_action: 0
    name_action: '1 arm'
    type_action: 0
  - description: ''
    id_action: 1
    name_action: '2 go to'
    type_action: 1
  - description: ''
    id_action: 2
    name_action: '3 arm'
    type_action: 0
  - description: ''
    id_action: 0
    name_action: '4 arm'
    type_action: 0
  - description: ''
    id_action: 1
    name_action: '5 go to'
    type_action: 1
  description: 'Test mission 2'
  id_mission: 1
  name_mission: 'test mission 2'
