(cl:in-package imu_manager-msg)
(cl:export '(HEADER-VAL
          HEADER
          CALIBRATION_STATUS-VAL
          CALIBRATION_STATUS
          NEXT_CHECK_COUNTDOWN-VAL
          NEXT_CHECK_COUNTDOWN
          CALIBRATION_DURATION-VAL
          CALIBRATION_DURATION
          IMU_TEMPERATURE-VAL
          IMU_TEMPERATURE
          CALIBRATED_IMU_TEMPERATURE-VAL
          CALIBRATED_IMU_TEMPERATURE
          ROBOT_MOVING-VAL
          ROBOT_MOVING
))