# START: start recording
# STOP: stop recording
# DISCARD: stop and discard recording
string STOP=stop
string START=start
string DISCARD=discard
string action

# Name of the bag file. If empty string, bag file will be named with date and time
string name
# Absolute path location folder to save the camera recordings
string path
---
# returns 0 if ok, -1 otherwise
bool success
string message
