// Generated by gencpp from file fake_joint_position_publisher/SetJoints.msg
// DO NOT EDIT!


#ifndef FAKE_JOINT_POSITION_PUBLISHER_MESSAGE_SETJOINTS_H
#define FAKE_JOINT_POSITION_PUBLISHER_MESSAGE_SETJOINTS_H

#include <ros/service_traits.h>


#include <fake_joint_position_publisher/SetJointsRequest.h>
#include <fake_joint_position_publisher/SetJointsResponse.h>


namespace fake_joint_position_publisher
{

struct SetJoints
{

typedef SetJointsRequest Request;
typedef SetJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJoints
} // namespace fake_joint_position_publisher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fake_joint_position_publisher::SetJoints > {
  static const char* value()
  {
    return "0f74c2ba51844f89cb01d50b436f6fba";
  }

  static const char* value(const ::fake_joint_position_publisher::SetJoints&) { return value(); }
};

template<>
struct DataType< ::fake_joint_position_publisher::SetJoints > {
  static const char* value()
  {
    return "fake_joint_position_publisher/SetJoints";
  }

  static const char* value(const ::fake_joint_position_publisher::SetJoints&) { return value(); }
};


// service_traits::MD5Sum< ::fake_joint_position_publisher::SetJointsRequest> should match
// service_traits::MD5Sum< ::fake_joint_position_publisher::SetJoints >
template<>
struct MD5Sum< ::fake_joint_position_publisher::SetJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fake_joint_position_publisher::SetJoints >::value();
  }
  static const char* value(const ::fake_joint_position_publisher::SetJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fake_joint_position_publisher::SetJointsRequest> should match
// service_traits::DataType< ::fake_joint_position_publisher::SetJoints >
template<>
struct DataType< ::fake_joint_position_publisher::SetJointsRequest>
{
  static const char* value()
  {
    return DataType< ::fake_joint_position_publisher::SetJoints >::value();
  }
  static const char* value(const ::fake_joint_position_publisher::SetJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fake_joint_position_publisher::SetJointsResponse> should match
// service_traits::MD5Sum< ::fake_joint_position_publisher::SetJoints >
template<>
struct MD5Sum< ::fake_joint_position_publisher::SetJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fake_joint_position_publisher::SetJoints >::value();
  }
  static const char* value(const ::fake_joint_position_publisher::SetJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fake_joint_position_publisher::SetJointsResponse> should match
// service_traits::DataType< ::fake_joint_position_publisher::SetJoints >
template<>
struct DataType< ::fake_joint_position_publisher::SetJointsResponse>
{
  static const char* value()
  {
    return DataType< ::fake_joint_position_publisher::SetJoints >::value();
  }
  static const char* value(const ::fake_joint_position_publisher::SetJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FAKE_JOINT_POSITION_PUBLISHER_MESSAGE_SETJOINTS_H
