// Generated by gencpp from file robot_local_control_msgs/ChargePetition.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_CHARGEPETITION_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_CHARGEPETITION_H

#include <ros/service_traits.h>


#include <robot_local_control_msgs/ChargePetitionRequest.h>
#include <robot_local_control_msgs/ChargePetitionResponse.h>


namespace robot_local_control_msgs
{

struct ChargePetition
{

typedef ChargePetitionRequest Request;
typedef ChargePetitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChargePetition
} // namespace robot_local_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_local_control_msgs::ChargePetition > {
  static const char* value()
  {
    return "d6d7f27a9204b33d4b52fe501814a3cf";
  }

  static const char* value(const ::robot_local_control_msgs::ChargePetition&) { return value(); }
};

template<>
struct DataType< ::robot_local_control_msgs::ChargePetition > {
  static const char* value()
  {
    return "robot_local_control_msgs/ChargePetition";
  }

  static const char* value(const ::robot_local_control_msgs::ChargePetition&) { return value(); }
};


// service_traits::MD5Sum< ::robot_local_control_msgs::ChargePetitionRequest> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::ChargePetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::ChargePetitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::ChargePetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::ChargePetitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::ChargePetitionRequest> should match
// service_traits::DataType< ::robot_local_control_msgs::ChargePetition >
template<>
struct DataType< ::robot_local_control_msgs::ChargePetitionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::ChargePetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::ChargePetitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_local_control_msgs::ChargePetitionResponse> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::ChargePetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::ChargePetitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::ChargePetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::ChargePetitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::ChargePetitionResponse> should match
// service_traits::DataType< ::robot_local_control_msgs::ChargePetition >
template<>
struct DataType< ::robot_local_control_msgs::ChargePetitionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::ChargePetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::ChargePetitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_CHARGEPETITION_H
