// Generated by gencpp from file robot_local_control_msgs/FindMagneticGuide.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_FINDMAGNETICGUIDE_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_FINDMAGNETICGUIDE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_local_control_msgs
{
template <class ContainerAllocator>
struct FindMagneticGuide_
{
  typedef FindMagneticGuide_<ContainerAllocator> Type;

  FindMagneticGuide_()
    : turn_direction()
    , in_distance(0.0)
    , lane(0)  {
    }
  FindMagneticGuide_(const ContainerAllocator& _alloc)
    : turn_direction(_alloc)
    , in_distance(0.0)
    , lane(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _turn_direction_type;
  _turn_direction_type turn_direction;

   typedef float _in_distance_type;
  _in_distance_type in_distance;

   typedef uint32_t _lane_type;
  _lane_type lane;





  typedef boost::shared_ptr< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> const> ConstPtr;

}; // struct FindMagneticGuide_

typedef ::robot_local_control_msgs::FindMagneticGuide_<std::allocator<void> > FindMagneticGuide;

typedef boost::shared_ptr< ::robot_local_control_msgs::FindMagneticGuide > FindMagneticGuidePtr;
typedef boost::shared_ptr< ::robot_local_control_msgs::FindMagneticGuide const> FindMagneticGuideConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator1> & lhs, const ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator2> & rhs)
{
  return lhs.turn_direction == rhs.turn_direction &&
    lhs.in_distance == rhs.in_distance &&
    lhs.lane == rhs.lane;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator1> & lhs, const ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_local_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be301344d82db2581c38425519475c66";
  }

  static const char* value(const ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe301344d82db258ULL;
  static const uint64_t static_value2 = 0x1c38425519475c66ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_local_control_msgs/FindMagneticGuide";
  }

  static const char* value(const ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#maximum distance to search the guide\n"
"string turn_direction\n"
"float32 in_distance\n"
"uint32 lane\n"
;
  }

  static const char* value(const ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turn_direction);
      stream.next(m.in_distance);
      stream.next(m.lane);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindMagneticGuide_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_local_control_msgs::FindMagneticGuide_<ContainerAllocator>& v)
  {
    s << indent << "turn_direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.turn_direction);
    s << indent << "in_distance: ";
    Printer<float>::stream(s, indent + "  ", v.in_distance);
    s << indent << "lane: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.lane);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_FINDMAGNETICGUIDE_H
