// Generated by gencpp from file robot_local_control_msgs/FindMagneticGuidePetition.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_FINDMAGNETICGUIDEPETITION_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_FINDMAGNETICGUIDEPETITION_H

#include <ros/service_traits.h>


#include <robot_local_control_msgs/FindMagneticGuidePetitionRequest.h>
#include <robot_local_control_msgs/FindMagneticGuidePetitionResponse.h>


namespace robot_local_control_msgs
{

struct FindMagneticGuidePetition
{

typedef FindMagneticGuidePetitionRequest Request;
typedef FindMagneticGuidePetitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindMagneticGuidePetition
} // namespace robot_local_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_local_control_msgs::FindMagneticGuidePetition > {
  static const char* value()
  {
    return "c389f8e9c0c15b3be21d4778fb3ad5bf";
  }

  static const char* value(const ::robot_local_control_msgs::FindMagneticGuidePetition&) { return value(); }
};

template<>
struct DataType< ::robot_local_control_msgs::FindMagneticGuidePetition > {
  static const char* value()
  {
    return "robot_local_control_msgs/FindMagneticGuidePetition";
  }

  static const char* value(const ::robot_local_control_msgs::FindMagneticGuidePetition&) { return value(); }
};


// service_traits::MD5Sum< ::robot_local_control_msgs::FindMagneticGuidePetitionRequest> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::FindMagneticGuidePetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::FindMagneticGuidePetitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::FindMagneticGuidePetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::FindMagneticGuidePetitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::FindMagneticGuidePetitionRequest> should match
// service_traits::DataType< ::robot_local_control_msgs::FindMagneticGuidePetition >
template<>
struct DataType< ::robot_local_control_msgs::FindMagneticGuidePetitionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::FindMagneticGuidePetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::FindMagneticGuidePetitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_local_control_msgs::FindMagneticGuidePetitionResponse> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::FindMagneticGuidePetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::FindMagneticGuidePetitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::FindMagneticGuidePetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::FindMagneticGuidePetitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::FindMagneticGuidePetitionResponse> should match
// service_traits::DataType< ::robot_local_control_msgs::FindMagneticGuidePetition >
template<>
struct DataType< ::robot_local_control_msgs::FindMagneticGuidePetitionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::FindMagneticGuidePetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::FindMagneticGuidePetitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_FINDMAGNETICGUIDEPETITION_H
