// Generated by gencpp from file robot_local_control_msgs/LeaveLiftPetition.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_LEAVELIFTPETITION_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_LEAVELIFTPETITION_H

#include <ros/service_traits.h>


#include <robot_local_control_msgs/LeaveLiftPetitionRequest.h>
#include <robot_local_control_msgs/LeaveLiftPetitionResponse.h>


namespace robot_local_control_msgs
{

struct LeaveLiftPetition
{

typedef LeaveLiftPetitionRequest Request;
typedef LeaveLiftPetitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LeaveLiftPetition
} // namespace robot_local_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_local_control_msgs::LeaveLiftPetition > {
  static const char* value()
  {
    return "ecdb7d18cedc65353c1996690a8c9cd1";
  }

  static const char* value(const ::robot_local_control_msgs::LeaveLiftPetition&) { return value(); }
};

template<>
struct DataType< ::robot_local_control_msgs::LeaveLiftPetition > {
  static const char* value()
  {
    return "robot_local_control_msgs/LeaveLiftPetition";
  }

  static const char* value(const ::robot_local_control_msgs::LeaveLiftPetition&) { return value(); }
};


// service_traits::MD5Sum< ::robot_local_control_msgs::LeaveLiftPetitionRequest> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::LeaveLiftPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::LeaveLiftPetitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::LeaveLiftPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::LeaveLiftPetitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::LeaveLiftPetitionRequest> should match
// service_traits::DataType< ::robot_local_control_msgs::LeaveLiftPetition >
template<>
struct DataType< ::robot_local_control_msgs::LeaveLiftPetitionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::LeaveLiftPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::LeaveLiftPetitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_local_control_msgs::LeaveLiftPetitionResponse> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::LeaveLiftPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::LeaveLiftPetitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::LeaveLiftPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::LeaveLiftPetitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::LeaveLiftPetitionResponse> should match
// service_traits::DataType< ::robot_local_control_msgs::LeaveLiftPetition >
template<>
struct DataType< ::robot_local_control_msgs::LeaveLiftPetitionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::LeaveLiftPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::LeaveLiftPetitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_LEAVELIFTPETITION_H
