// Generated by gencpp from file robot_local_control_msgs/MissionCommandPetitionRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_MISSIONCOMMANDPETITIONREQUEST_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_MISSIONCOMMANDPETITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_local_control_msgs/MissionCommand.h>

namespace robot_local_control_msgs
{
template <class ContainerAllocator>
struct MissionCommandPetitionRequest_
{
  typedef MissionCommandPetitionRequest_<ContainerAllocator> Type;

  MissionCommandPetitionRequest_()
    : command()  {
    }
  MissionCommandPetitionRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robot_local_control_msgs::MissionCommand_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MissionCommandPetitionRequest_

typedef ::robot_local_control_msgs::MissionCommandPetitionRequest_<std::allocator<void> > MissionCommandPetitionRequest;

typedef boost::shared_ptr< ::robot_local_control_msgs::MissionCommandPetitionRequest > MissionCommandPetitionRequestPtr;
typedef boost::shared_ptr< ::robot_local_control_msgs::MissionCommandPetitionRequest const> MissionCommandPetitionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator1> & lhs, const ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator1> & lhs, const ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_local_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0974609f2dac5dfd138a7ae7e5461fb9";
  }

  static const char* value(const ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0974609f2dac5dfdULL;
  static const uint64_t static_value2 = 0x138a7ae7e5461fb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_local_control_msgs/MissionCommandPetitionRequest";
  }

  static const char* value(const ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MissionCommand command\n"
"\n"
"================================================================================\n"
"MSG: robot_local_control_msgs/MissionCommand\n"
"# XXX: DO NOT USE THIS MESSAGE\n"
"# available commands\n"
"string GOTO_POSE=goto_pose\n"
"string GOTO_TAG=goto_tag\n"
"string GOTO_NODE=goto_node\n"
"\n"
"# id set from the subsystem calling the service\n"
"int32 id\n"
"# command from the available commands\n"
"string command\n"
"\n"
"MissionParamInt[] int_params\n"
"MissionParamFloat[] float_params\n"
"MissionParamString[] string_params\n"
"MissionParamBool[] bool_params\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robot_local_control_msgs/MissionParamInt\n"
"# param name\n"
"string name\n"
"# param value\n"
"int32 value\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robot_local_control_msgs/MissionParamFloat\n"
"# param name\n"
"string name\n"
"# param value\n"
"float32 value\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robot_local_control_msgs/MissionParamString\n"
"# param name\n"
"string name\n"
"# param value\n"
"string value\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robot_local_control_msgs/MissionParamBool\n"
"# param name\n"
"string name\n"
"# param value\n"
"bool value\n"
"\n"
;
  }

  static const char* value(const ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionCommandPetitionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_local_control_msgs::MissionCommandPetitionRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    s << std::endl;
    Printer< ::robot_local_control_msgs::MissionCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_MISSIONCOMMANDPETITIONREQUEST_H
