// Generated by gencpp from file robot_local_control_msgs/MissionParamFloat.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_MISSIONPARAMFLOAT_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_MISSIONPARAMFLOAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_local_control_msgs
{
template <class ContainerAllocator>
struct MissionParamFloat_
{
  typedef MissionParamFloat_<ContainerAllocator> Type;

  MissionParamFloat_()
    : name()
    , value(0.0)  {
    }
  MissionParamFloat_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef float _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> const> ConstPtr;

}; // struct MissionParamFloat_

typedef ::robot_local_control_msgs::MissionParamFloat_<std::allocator<void> > MissionParamFloat;

typedef boost::shared_ptr< ::robot_local_control_msgs::MissionParamFloat > MissionParamFloatPtr;
typedef boost::shared_ptr< ::robot_local_control_msgs::MissionParamFloat const> MissionParamFloatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator1> & lhs, const ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator1> & lhs, const ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_local_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db3486341a840969e8845548decf6f11";
  }

  static const char* value(const ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb3486341a840969ULL;
  static const uint64_t static_value2 = 0xe8845548decf6f11ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_local_control_msgs/MissionParamFloat";
  }

  static const char* value(const ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# param name\n"
"string name\n"
"# param value\n"
"float32 value\n"
"\n"
;
  }

  static const char* value(const ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionParamFloat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_local_control_msgs::MissionParamFloat_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_MISSIONPARAMFLOAT_H
