// Generated by gencpp from file robot_local_control_msgs/MissionPetition.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_MISSIONPETITION_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_MISSIONPETITION_H

#include <ros/service_traits.h>


#include <robot_local_control_msgs/MissionPetitionRequest.h>
#include <robot_local_control_msgs/MissionPetitionResponse.h>


namespace robot_local_control_msgs
{

struct MissionPetition
{

typedef MissionPetitionRequest Request;
typedef MissionPetitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionPetition
} // namespace robot_local_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_local_control_msgs::MissionPetition > {
  static const char* value()
  {
    return "d23b48ec07b484e69921f98c567e661e";
  }

  static const char* value(const ::robot_local_control_msgs::MissionPetition&) { return value(); }
};

template<>
struct DataType< ::robot_local_control_msgs::MissionPetition > {
  static const char* value()
  {
    return "robot_local_control_msgs/MissionPetition";
  }

  static const char* value(const ::robot_local_control_msgs::MissionPetition&) { return value(); }
};


// service_traits::MD5Sum< ::robot_local_control_msgs::MissionPetitionRequest> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::MissionPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::MissionPetitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::MissionPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::MissionPetitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::MissionPetitionRequest> should match
// service_traits::DataType< ::robot_local_control_msgs::MissionPetition >
template<>
struct DataType< ::robot_local_control_msgs::MissionPetitionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::MissionPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::MissionPetitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_local_control_msgs::MissionPetitionResponse> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::MissionPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::MissionPetitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::MissionPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::MissionPetitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::MissionPetitionResponse> should match
// service_traits::DataType< ::robot_local_control_msgs::MissionPetition >
template<>
struct DataType< ::robot_local_control_msgs::MissionPetitionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::MissionPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::MissionPetitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_MISSIONPETITION_H
