// Generated by gencpp from file robot_local_control_msgs/MissionCommandPetition.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_MISSIONCOMMANDPETITION_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_MISSIONCOMMANDPETITION_H

#include <ros/service_traits.h>


#include <robot_local_control_msgs/MissionCommandPetitionRequest.h>
#include <robot_local_control_msgs/MissionCommandPetitionResponse.h>


namespace robot_local_control_msgs
{

struct MissionCommandPetition
{

typedef MissionCommandPetitionRequest Request;
typedef MissionCommandPetitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionCommandPetition
} // namespace robot_local_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_local_control_msgs::MissionCommandPetition > {
  static const char* value()
  {
    return "09baf2a641d8c856ea25723a419f07b4";
  }

  static const char* value(const ::robot_local_control_msgs::MissionCommandPetition&) { return value(); }
};

template<>
struct DataType< ::robot_local_control_msgs::MissionCommandPetition > {
  static const char* value()
  {
    return "robot_local_control_msgs/MissionCommandPetition";
  }

  static const char* value(const ::robot_local_control_msgs::MissionCommandPetition&) { return value(); }
};


// service_traits::MD5Sum< ::robot_local_control_msgs::MissionCommandPetitionRequest> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::MissionCommandPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::MissionCommandPetitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::MissionCommandPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::MissionCommandPetitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::MissionCommandPetitionRequest> should match
// service_traits::DataType< ::robot_local_control_msgs::MissionCommandPetition >
template<>
struct DataType< ::robot_local_control_msgs::MissionCommandPetitionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::MissionCommandPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::MissionCommandPetitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_local_control_msgs::MissionCommandPetitionResponse> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::MissionCommandPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::MissionCommandPetitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::MissionCommandPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::MissionCommandPetitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::MissionCommandPetitionResponse> should match
// service_traits::DataType< ::robot_local_control_msgs::MissionCommandPetition >
template<>
struct DataType< ::robot_local_control_msgs::MissionCommandPetitionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::MissionCommandPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::MissionCommandPetitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_MISSIONCOMMANDPETITION_H
