// Generated by gencpp from file robot_local_control_msgs/PickPetition.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_PICKPETITION_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_PICKPETITION_H

#include <ros/service_traits.h>


#include <robot_local_control_msgs/PickPetitionRequest.h>
#include <robot_local_control_msgs/PickPetitionResponse.h>


namespace robot_local_control_msgs
{

struct PickPetition
{

typedef PickPetitionRequest Request;
typedef PickPetitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PickPetition
} // namespace robot_local_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_local_control_msgs::PickPetition > {
  static const char* value()
  {
    return "44c7093f5d45a75a03470d3d82ca14f6";
  }

  static const char* value(const ::robot_local_control_msgs::PickPetition&) { return value(); }
};

template<>
struct DataType< ::robot_local_control_msgs::PickPetition > {
  static const char* value()
  {
    return "robot_local_control_msgs/PickPetition";
  }

  static const char* value(const ::robot_local_control_msgs::PickPetition&) { return value(); }
};


// service_traits::MD5Sum< ::robot_local_control_msgs::PickPetitionRequest> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::PickPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::PickPetitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::PickPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::PickPetitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::PickPetitionRequest> should match
// service_traits::DataType< ::robot_local_control_msgs::PickPetition >
template<>
struct DataType< ::robot_local_control_msgs::PickPetitionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::PickPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::PickPetitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_local_control_msgs::PickPetitionResponse> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::PickPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::PickPetitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::PickPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::PickPetitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::PickPetitionResponse> should match
// service_traits::DataType< ::robot_local_control_msgs::PickPetition >
template<>
struct DataType< ::robot_local_control_msgs::PickPetitionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::PickPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::PickPetitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_PICKPETITION_H
