// Generated by gencpp from file robot_local_control_msgs/PostPickPetition.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_POSTPICKPETITION_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_POSTPICKPETITION_H

#include <ros/service_traits.h>


#include <robot_local_control_msgs/PostPickPetitionRequest.h>
#include <robot_local_control_msgs/PostPickPetitionResponse.h>


namespace robot_local_control_msgs
{

struct PostPickPetition
{

typedef PostPickPetitionRequest Request;
typedef PostPickPetitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PostPickPetition
} // namespace robot_local_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_local_control_msgs::PostPickPetition > {
  static const char* value()
  {
    return "128b8c48c0209b2b9cf5cb28ef7c6494";
  }

  static const char* value(const ::robot_local_control_msgs::PostPickPetition&) { return value(); }
};

template<>
struct DataType< ::robot_local_control_msgs::PostPickPetition > {
  static const char* value()
  {
    return "robot_local_control_msgs/PostPickPetition";
  }

  static const char* value(const ::robot_local_control_msgs::PostPickPetition&) { return value(); }
};


// service_traits::MD5Sum< ::robot_local_control_msgs::PostPickPetitionRequest> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::PostPickPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::PostPickPetitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::PostPickPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::PostPickPetitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::PostPickPetitionRequest> should match
// service_traits::DataType< ::robot_local_control_msgs::PostPickPetition >
template<>
struct DataType< ::robot_local_control_msgs::PostPickPetitionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::PostPickPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::PostPickPetitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_local_control_msgs::PostPickPetitionResponse> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::PostPickPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::PostPickPetitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::PostPickPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::PostPickPetitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::PostPickPetitionResponse> should match
// service_traits::DataType< ::robot_local_control_msgs::PostPickPetition >
template<>
struct DataType< ::robot_local_control_msgs::PostPickPetitionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::PostPickPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::PostPickPetitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_POSTPICKPETITION_H
