// Generated by gencpp from file robot_local_control_msgs/PrePickPetitionRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_PREPICKPETITIONREQUEST_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_PREPICKPETITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_local_control_msgs/PrePick.h>

namespace robot_local_control_msgs
{
template <class ContainerAllocator>
struct PrePickPetitionRequest_
{
  typedef PrePickPetitionRequest_<ContainerAllocator> Type;

  PrePickPetitionRequest_()
    : procedure()  {
    }
  PrePickPetitionRequest_(const ContainerAllocator& _alloc)
    : procedure(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robot_local_control_msgs::PrePick_<ContainerAllocator>  _procedure_type;
  _procedure_type procedure;





  typedef boost::shared_ptr< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PrePickPetitionRequest_

typedef ::robot_local_control_msgs::PrePickPetitionRequest_<std::allocator<void> > PrePickPetitionRequest;

typedef boost::shared_ptr< ::robot_local_control_msgs::PrePickPetitionRequest > PrePickPetitionRequestPtr;
typedef boost::shared_ptr< ::robot_local_control_msgs::PrePickPetitionRequest const> PrePickPetitionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator1> & lhs, const ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.procedure == rhs.procedure;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator1> & lhs, const ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_local_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac0f0c4fc334c16be9f001ec3176094a";
  }

  static const char* value(const ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac0f0c4fc334c16bULL;
  static const uint64_t static_value2 = 0xe9f001ec3176094aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_local_control_msgs/PrePickPetitionRequest";
  }

  static const char* value(const ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PrePick procedure \n"
"\n"
"================================================================================\n"
"MSG: robot_local_control_msgs/PrePick\n"
"string turn_direction\n"
;
  }

  static const char* value(const ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.procedure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PrePickPetitionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_local_control_msgs::PrePickPetitionRequest_<ContainerAllocator>& v)
  {
    s << indent << "procedure: ";
    s << std::endl;
    Printer< ::robot_local_control_msgs::PrePick_<ContainerAllocator> >::stream(s, indent + "  ", v.procedure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_PREPICKPETITIONREQUEST_H
