// Generated by gencpp from file robot_local_control_msgs/SetControlState.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_SETCONTROLSTATE_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_SETCONTROLSTATE_H

#include <ros/service_traits.h>


#include <robot_local_control_msgs/SetControlStateRequest.h>
#include <robot_local_control_msgs/SetControlStateResponse.h>


namespace robot_local_control_msgs
{

struct SetControlState
{

typedef SetControlStateRequest Request;
typedef SetControlStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetControlState
} // namespace robot_local_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_local_control_msgs::SetControlState > {
  static const char* value()
  {
    return "c348f8d8cd3a80f54328aa4159009109";
  }

  static const char* value(const ::robot_local_control_msgs::SetControlState&) { return value(); }
};

template<>
struct DataType< ::robot_local_control_msgs::SetControlState > {
  static const char* value()
  {
    return "robot_local_control_msgs/SetControlState";
  }

  static const char* value(const ::robot_local_control_msgs::SetControlState&) { return value(); }
};


// service_traits::MD5Sum< ::robot_local_control_msgs::SetControlStateRequest> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::SetControlState >
template<>
struct MD5Sum< ::robot_local_control_msgs::SetControlStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::SetControlState >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SetControlStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::SetControlStateRequest> should match
// service_traits::DataType< ::robot_local_control_msgs::SetControlState >
template<>
struct DataType< ::robot_local_control_msgs::SetControlStateRequest>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::SetControlState >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SetControlStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_local_control_msgs::SetControlStateResponse> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::SetControlState >
template<>
struct MD5Sum< ::robot_local_control_msgs::SetControlStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::SetControlState >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SetControlStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::SetControlStateResponse> should match
// service_traits::DataType< ::robot_local_control_msgs::SetControlState >
template<>
struct DataType< ::robot_local_control_msgs::SetControlStateResponse>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::SetControlState >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SetControlStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_SETCONTROLSTATE_H
