// Generated by gencpp from file robot_local_control_msgs/SetFrameID.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_SETFRAMEID_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_SETFRAMEID_H

#include <ros/service_traits.h>


#include <robot_local_control_msgs/SetFrameIDRequest.h>
#include <robot_local_control_msgs/SetFrameIDResponse.h>


namespace robot_local_control_msgs
{

struct SetFrameID
{

typedef SetFrameIDRequest Request;
typedef SetFrameIDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFrameID
} // namespace robot_local_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_local_control_msgs::SetFrameID > {
  static const char* value()
  {
    return "35f2ba3133054633678b5f61278846ec";
  }

  static const char* value(const ::robot_local_control_msgs::SetFrameID&) { return value(); }
};

template<>
struct DataType< ::robot_local_control_msgs::SetFrameID > {
  static const char* value()
  {
    return "robot_local_control_msgs/SetFrameID";
  }

  static const char* value(const ::robot_local_control_msgs::SetFrameID&) { return value(); }
};


// service_traits::MD5Sum< ::robot_local_control_msgs::SetFrameIDRequest> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::SetFrameID >
template<>
struct MD5Sum< ::robot_local_control_msgs::SetFrameIDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::SetFrameID >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SetFrameIDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::SetFrameIDRequest> should match
// service_traits::DataType< ::robot_local_control_msgs::SetFrameID >
template<>
struct DataType< ::robot_local_control_msgs::SetFrameIDRequest>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::SetFrameID >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SetFrameIDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_local_control_msgs::SetFrameIDResponse> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::SetFrameID >
template<>
struct MD5Sum< ::robot_local_control_msgs::SetFrameIDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::SetFrameID >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SetFrameIDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::SetFrameIDResponse> should match
// service_traits::DataType< ::robot_local_control_msgs::SetFrameID >
template<>
struct DataType< ::robot_local_control_msgs::SetFrameIDResponse>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::SetFrameID >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SetFrameIDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_SETFRAMEID_H
