// Generated by gencpp from file robot_local_control_msgs/SetGoToPetition.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_SETGOTOPETITION_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_SETGOTOPETITION_H

#include <ros/service_traits.h>


#include <robot_local_control_msgs/SetGoToPetitionRequest.h>
#include <robot_local_control_msgs/SetGoToPetitionResponse.h>


namespace robot_local_control_msgs
{

struct SetGoToPetition
{

typedef SetGoToPetitionRequest Request;
typedef SetGoToPetitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGoToPetition
} // namespace robot_local_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_local_control_msgs::SetGoToPetition > {
  static const char* value()
  {
    return "113a2cfed66fa5447f35250c8468af29";
  }

  static const char* value(const ::robot_local_control_msgs::SetGoToPetition&) { return value(); }
};

template<>
struct DataType< ::robot_local_control_msgs::SetGoToPetition > {
  static const char* value()
  {
    return "robot_local_control_msgs/SetGoToPetition";
  }

  static const char* value(const ::robot_local_control_msgs::SetGoToPetition&) { return value(); }
};


// service_traits::MD5Sum< ::robot_local_control_msgs::SetGoToPetitionRequest> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::SetGoToPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::SetGoToPetitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::SetGoToPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SetGoToPetitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::SetGoToPetitionRequest> should match
// service_traits::DataType< ::robot_local_control_msgs::SetGoToPetition >
template<>
struct DataType< ::robot_local_control_msgs::SetGoToPetitionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::SetGoToPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SetGoToPetitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_local_control_msgs::SetGoToPetitionResponse> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::SetGoToPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::SetGoToPetitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::SetGoToPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SetGoToPetitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::SetGoToPetitionResponse> should match
// service_traits::DataType< ::robot_local_control_msgs::SetGoToPetition >
template<>
struct DataType< ::robot_local_control_msgs::SetGoToPetitionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::SetGoToPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SetGoToPetitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_SETGOTOPETITION_H
