// Generated by gencpp from file robot_local_control_msgs/SwitchMapPetition.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_SWITCHMAPPETITION_H
#define ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_SWITCHMAPPETITION_H

#include <ros/service_traits.h>


#include <robot_local_control_msgs/SwitchMapPetitionRequest.h>
#include <robot_local_control_msgs/SwitchMapPetitionResponse.h>


namespace robot_local_control_msgs
{

struct SwitchMapPetition
{

typedef SwitchMapPetitionRequest Request;
typedef SwitchMapPetitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchMapPetition
} // namespace robot_local_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_local_control_msgs::SwitchMapPetition > {
  static const char* value()
  {
    return "2bfe0dcd456b842958098fba699b2d25";
  }

  static const char* value(const ::robot_local_control_msgs::SwitchMapPetition&) { return value(); }
};

template<>
struct DataType< ::robot_local_control_msgs::SwitchMapPetition > {
  static const char* value()
  {
    return "robot_local_control_msgs/SwitchMapPetition";
  }

  static const char* value(const ::robot_local_control_msgs::SwitchMapPetition&) { return value(); }
};


// service_traits::MD5Sum< ::robot_local_control_msgs::SwitchMapPetitionRequest> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::SwitchMapPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::SwitchMapPetitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::SwitchMapPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SwitchMapPetitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::SwitchMapPetitionRequest> should match
// service_traits::DataType< ::robot_local_control_msgs::SwitchMapPetition >
template<>
struct DataType< ::robot_local_control_msgs::SwitchMapPetitionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::SwitchMapPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SwitchMapPetitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_local_control_msgs::SwitchMapPetitionResponse> should match
// service_traits::MD5Sum< ::robot_local_control_msgs::SwitchMapPetition >
template<>
struct MD5Sum< ::robot_local_control_msgs::SwitchMapPetitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_local_control_msgs::SwitchMapPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SwitchMapPetitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_local_control_msgs::SwitchMapPetitionResponse> should match
// service_traits::DataType< ::robot_local_control_msgs::SwitchMapPetition >
template<>
struct DataType< ::robot_local_control_msgs::SwitchMapPetitionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_local_control_msgs::SwitchMapPetition >::value();
  }
  static const char* value(const ::robot_local_control_msgs::SwitchMapPetitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MSGS_MESSAGE_SWITCHMAPPETITION_H
