// Generated by gencpp from file robot_simple_command_manager_msgs/CommandManagerArray.msg
// DO NOT EDIT!


#ifndef ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_COMMANDMANAGERARRAY_H
#define ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_COMMANDMANAGERARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_simple_command_manager_msgs/CommandManager.h>

namespace robot_simple_command_manager_msgs
{
template <class ContainerAllocator>
struct CommandManagerArray_
{
  typedef CommandManagerArray_<ContainerAllocator> Type;

  CommandManagerArray_()
    : commands()  {
    }
  CommandManagerArray_(const ContainerAllocator& _alloc)
    : commands(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robot_simple_command_manager_msgs::CommandManager_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robot_simple_command_manager_msgs::CommandManager_<ContainerAllocator> >::other >  _commands_type;
  _commands_type commands;





  typedef boost::shared_ptr< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> const> ConstPtr;

}; // struct CommandManagerArray_

typedef ::robot_simple_command_manager_msgs::CommandManagerArray_<std::allocator<void> > CommandManagerArray;

typedef boost::shared_ptr< ::robot_simple_command_manager_msgs::CommandManagerArray > CommandManagerArrayPtr;
typedef boost::shared_ptr< ::robot_simple_command_manager_msgs::CommandManagerArray const> CommandManagerArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator1> & lhs, const ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator2> & rhs)
{
  return lhs.commands == rhs.commands;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator1> & lhs, const ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_simple_command_manager_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0921f1afc8f4127f55f1c0b6e23fe8bd";
  }

  static const char* value(const ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0921f1afc8f4127fULL;
  static const uint64_t static_value2 = 0x55f1c0b6e23fe8bdULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_simple_command_manager_msgs/CommandManagerArray";
  }

  static const char* value(const ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_simple_command_manager_msgs/CommandManager[] commands\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robot_simple_command_manager_msgs/CommandManager\n"
"string id\n"
"string command\n"
"\n"
;
  }

  static const char* value(const ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.commands);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandManagerArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_simple_command_manager_msgs::CommandManagerArray_<ContainerAllocator>& v)
  {
    s << indent << "commands[]" << std::endl;
    for (size_t i = 0; i < v.commands.size(); ++i)
    {
      s << indent << "  commands[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robot_simple_command_manager_msgs::CommandManager_<ContainerAllocator> >::stream(s, indent + "    ", v.commands[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_COMMANDMANAGERARRAY_H
