// Generated by gencpp from file robot_simple_command_manager_msgs/GetCommandManagerList.msg
// DO NOT EDIT!


#ifndef ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_GETCOMMANDMANAGERLIST_H
#define ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_GETCOMMANDMANAGERLIST_H

#include <ros/service_traits.h>


#include <robot_simple_command_manager_msgs/GetCommandManagerListRequest.h>
#include <robot_simple_command_manager_msgs/GetCommandManagerListResponse.h>


namespace robot_simple_command_manager_msgs
{

struct GetCommandManagerList
{

typedef GetCommandManagerListRequest Request;
typedef GetCommandManagerListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCommandManagerList
} // namespace robot_simple_command_manager_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_simple_command_manager_msgs::GetCommandManagerList > {
  static const char* value()
  {
    return "efa7801a29cc81feaf45e89c194507dc";
  }

  static const char* value(const ::robot_simple_command_manager_msgs::GetCommandManagerList&) { return value(); }
};

template<>
struct DataType< ::robot_simple_command_manager_msgs::GetCommandManagerList > {
  static const char* value()
  {
    return "robot_simple_command_manager_msgs/GetCommandManagerList";
  }

  static const char* value(const ::robot_simple_command_manager_msgs::GetCommandManagerList&) { return value(); }
};


// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::GetCommandManagerListRequest> should match
// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::GetCommandManagerList >
template<>
struct MD5Sum< ::robot_simple_command_manager_msgs::GetCommandManagerListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_simple_command_manager_msgs::GetCommandManagerList >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::GetCommandManagerListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_simple_command_manager_msgs::GetCommandManagerListRequest> should match
// service_traits::DataType< ::robot_simple_command_manager_msgs::GetCommandManagerList >
template<>
struct DataType< ::robot_simple_command_manager_msgs::GetCommandManagerListRequest>
{
  static const char* value()
  {
    return DataType< ::robot_simple_command_manager_msgs::GetCommandManagerList >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::GetCommandManagerListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::GetCommandManagerListResponse> should match
// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::GetCommandManagerList >
template<>
struct MD5Sum< ::robot_simple_command_manager_msgs::GetCommandManagerListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_simple_command_manager_msgs::GetCommandManagerList >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::GetCommandManagerListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_simple_command_manager_msgs::GetCommandManagerListResponse> should match
// service_traits::DataType< ::robot_simple_command_manager_msgs::GetCommandManagerList >
template<>
struct DataType< ::robot_simple_command_manager_msgs::GetCommandManagerListResponse>
{
  static const char* value()
  {
    return DataType< ::robot_simple_command_manager_msgs::GetCommandManagerList >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::GetCommandManagerListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_GETCOMMANDMANAGERLIST_H
