// Generated by gencpp from file robot_simple_command_manager_msgs/GetHandlerInfo.msg
// DO NOT EDIT!


#ifndef ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_GETHANDLERINFO_H
#define ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_GETHANDLERINFO_H

#include <ros/service_traits.h>


#include <robot_simple_command_manager_msgs/GetHandlerInfoRequest.h>
#include <robot_simple_command_manager_msgs/GetHandlerInfoResponse.h>


namespace robot_simple_command_manager_msgs
{

struct GetHandlerInfo
{

typedef GetHandlerInfoRequest Request;
typedef GetHandlerInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHandlerInfo
} // namespace robot_simple_command_manager_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_simple_command_manager_msgs::GetHandlerInfo > {
  static const char* value()
  {
    return "5255a97f7f207306f16086ffc767a36b";
  }

  static const char* value(const ::robot_simple_command_manager_msgs::GetHandlerInfo&) { return value(); }
};

template<>
struct DataType< ::robot_simple_command_manager_msgs::GetHandlerInfo > {
  static const char* value()
  {
    return "robot_simple_command_manager_msgs/GetHandlerInfo";
  }

  static const char* value(const ::robot_simple_command_manager_msgs::GetHandlerInfo&) { return value(); }
};


// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::GetHandlerInfoRequest> should match
// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::GetHandlerInfo >
template<>
struct MD5Sum< ::robot_simple_command_manager_msgs::GetHandlerInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_simple_command_manager_msgs::GetHandlerInfo >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::GetHandlerInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_simple_command_manager_msgs::GetHandlerInfoRequest> should match
// service_traits::DataType< ::robot_simple_command_manager_msgs::GetHandlerInfo >
template<>
struct DataType< ::robot_simple_command_manager_msgs::GetHandlerInfoRequest>
{
  static const char* value()
  {
    return DataType< ::robot_simple_command_manager_msgs::GetHandlerInfo >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::GetHandlerInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::GetHandlerInfoResponse> should match
// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::GetHandlerInfo >
template<>
struct MD5Sum< ::robot_simple_command_manager_msgs::GetHandlerInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_simple_command_manager_msgs::GetHandlerInfo >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::GetHandlerInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_simple_command_manager_msgs::GetHandlerInfoResponse> should match
// service_traits::DataType< ::robot_simple_command_manager_msgs::GetHandlerInfo >
template<>
struct DataType< ::robot_simple_command_manager_msgs::GetHandlerInfoResponse>
{
  static const char* value()
  {
    return DataType< ::robot_simple_command_manager_msgs::GetHandlerInfo >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::GetHandlerInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_GETHANDLERINFO_H
