// Generated by gencpp from file robot_simple_command_manager_msgs/GetHandlers.msg
// DO NOT EDIT!


#ifndef ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_GETHANDLERS_H
#define ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_GETHANDLERS_H

#include <ros/service_traits.h>


#include <robot_simple_command_manager_msgs/GetHandlersRequest.h>
#include <robot_simple_command_manager_msgs/GetHandlersResponse.h>


namespace robot_simple_command_manager_msgs
{

struct GetHandlers
{

typedef GetHandlersRequest Request;
typedef GetHandlersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHandlers
} // namespace robot_simple_command_manager_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_simple_command_manager_msgs::GetHandlers > {
  static const char* value()
  {
    return "dd8c5aa023d5f8392d90b9573cfc34a5";
  }

  static const char* value(const ::robot_simple_command_manager_msgs::GetHandlers&) { return value(); }
};

template<>
struct DataType< ::robot_simple_command_manager_msgs::GetHandlers > {
  static const char* value()
  {
    return "robot_simple_command_manager_msgs/GetHandlers";
  }

  static const char* value(const ::robot_simple_command_manager_msgs::GetHandlers&) { return value(); }
};


// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::GetHandlersRequest> should match
// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::GetHandlers >
template<>
struct MD5Sum< ::robot_simple_command_manager_msgs::GetHandlersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_simple_command_manager_msgs::GetHandlers >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::GetHandlersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_simple_command_manager_msgs::GetHandlersRequest> should match
// service_traits::DataType< ::robot_simple_command_manager_msgs::GetHandlers >
template<>
struct DataType< ::robot_simple_command_manager_msgs::GetHandlersRequest>
{
  static const char* value()
  {
    return DataType< ::robot_simple_command_manager_msgs::GetHandlers >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::GetHandlersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::GetHandlersResponse> should match
// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::GetHandlers >
template<>
struct MD5Sum< ::robot_simple_command_manager_msgs::GetHandlersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_simple_command_manager_msgs::GetHandlers >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::GetHandlersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_simple_command_manager_msgs::GetHandlersResponse> should match
// service_traits::DataType< ::robot_simple_command_manager_msgs::GetHandlers >
template<>
struct DataType< ::robot_simple_command_manager_msgs::GetHandlersResponse>
{
  static const char* value()
  {
    return DataType< ::robot_simple_command_manager_msgs::GetHandlers >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::GetHandlersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_GETHANDLERS_H
