// Generated by gencpp from file robot_simple_command_manager_msgs/RobotSimpleCommandGoal.msg
// DO NOT EDIT!


#ifndef ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_ROBOTSIMPLECOMMANDGOAL_H
#define ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_ROBOTSIMPLECOMMANDGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_simple_command_manager_msgs/CommandString.h>

namespace robot_simple_command_manager_msgs
{
template <class ContainerAllocator>
struct RobotSimpleCommandGoal_
{
  typedef RobotSimpleCommandGoal_<ContainerAllocator> Type;

  RobotSimpleCommandGoal_()
    : command()  {
    }
  RobotSimpleCommandGoal_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robot_simple_command_manager_msgs::CommandString_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RobotSimpleCommandGoal_

typedef ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<std::allocator<void> > RobotSimpleCommandGoal;

typedef boost::shared_ptr< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal > RobotSimpleCommandGoalPtr;
typedef boost::shared_ptr< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal const> RobotSimpleCommandGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator1> & lhs, const ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator1> & lhs, const ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_simple_command_manager_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e08de5566abfe6f1c75d4e9dad2931d";
  }

  static const char* value(const ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e08de5566abfe6fULL;
  static const uint64_t static_value2 = 0x1c75d4e9dad2931dULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_simple_command_manager_msgs/RobotSimpleCommandGoal";
  }

  static const char* value(const ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"robot_simple_command_manager_msgs/CommandString command\n"
"\n"
"================================================================================\n"
"MSG: robot_simple_command_manager_msgs/CommandString\n"
"string command\n"
;
  }

  static const char* value(const ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotSimpleCommandGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_simple_command_manager_msgs::RobotSimpleCommandGoal_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    s << std::endl;
    Printer< ::robot_simple_command_manager_msgs::CommandString_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_ROBOTSIMPLECOMMANDGOAL_H
