// Generated by gencpp from file robot_simple_command_manager_msgs/SetCommandString.msg
// DO NOT EDIT!


#ifndef ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_SETCOMMANDSTRING_H
#define ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_SETCOMMANDSTRING_H

#include <ros/service_traits.h>


#include <robot_simple_command_manager_msgs/SetCommandStringRequest.h>
#include <robot_simple_command_manager_msgs/SetCommandStringResponse.h>


namespace robot_simple_command_manager_msgs
{

struct SetCommandString
{

typedef SetCommandStringRequest Request;
typedef SetCommandStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCommandString
} // namespace robot_simple_command_manager_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_simple_command_manager_msgs::SetCommandString > {
  static const char* value()
  {
    return "a562ec88e0fa4ca847fa743945bf6490";
  }

  static const char* value(const ::robot_simple_command_manager_msgs::SetCommandString&) { return value(); }
};

template<>
struct DataType< ::robot_simple_command_manager_msgs::SetCommandString > {
  static const char* value()
  {
    return "robot_simple_command_manager_msgs/SetCommandString";
  }

  static const char* value(const ::robot_simple_command_manager_msgs::SetCommandString&) { return value(); }
};


// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::SetCommandStringRequest> should match
// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::SetCommandString >
template<>
struct MD5Sum< ::robot_simple_command_manager_msgs::SetCommandStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_simple_command_manager_msgs::SetCommandString >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::SetCommandStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_simple_command_manager_msgs::SetCommandStringRequest> should match
// service_traits::DataType< ::robot_simple_command_manager_msgs::SetCommandString >
template<>
struct DataType< ::robot_simple_command_manager_msgs::SetCommandStringRequest>
{
  static const char* value()
  {
    return DataType< ::robot_simple_command_manager_msgs::SetCommandString >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::SetCommandStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::SetCommandStringResponse> should match
// service_traits::MD5Sum< ::robot_simple_command_manager_msgs::SetCommandString >
template<>
struct MD5Sum< ::robot_simple_command_manager_msgs::SetCommandStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_simple_command_manager_msgs::SetCommandString >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::SetCommandStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_simple_command_manager_msgs::SetCommandStringResponse> should match
// service_traits::DataType< ::robot_simple_command_manager_msgs::SetCommandString >
template<>
struct DataType< ::robot_simple_command_manager_msgs::SetCommandStringResponse>
{
  static const char* value()
  {
    return DataType< ::robot_simple_command_manager_msgs::SetCommandString >::value();
  }
  static const char* value(const ::robot_simple_command_manager_msgs::SetCommandStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SIMPLE_COMMAND_MANAGER_MSGS_MESSAGE_SETCOMMANDSTRING_H
