// Generated by gencpp from file system_monitor/CPUTemperatureStatus.msg
// DO NOT EDIT!


#ifndef SYSTEM_MONITOR_MESSAGE_CPUTEMPERATURESTATUS_H
#define SYSTEM_MONITOR_MESSAGE_CPUTEMPERATURESTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <system_monitor/CoreTemp.h>

namespace system_monitor
{
template <class ContainerAllocator>
struct CPUTemperatureStatus_
{
  typedef CPUTemperatureStatus_<ContainerAllocator> Type;

  CPUTemperatureStatus_()
    : status()
    , time(0.0)
    , cores()  {
    }
  CPUTemperatureStatus_(const ContainerAllocator& _alloc)
    : status(_alloc)
    , time(0.0)
    , cores(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;

   typedef float _time_type;
  _time_type time;

   typedef std::vector< ::system_monitor::CoreTemp_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::system_monitor::CoreTemp_<ContainerAllocator> >::other >  _cores_type;
  _cores_type cores;





  typedef boost::shared_ptr< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> const> ConstPtr;

}; // struct CPUTemperatureStatus_

typedef ::system_monitor::CPUTemperatureStatus_<std::allocator<void> > CPUTemperatureStatus;

typedef boost::shared_ptr< ::system_monitor::CPUTemperatureStatus > CPUTemperatureStatusPtr;
typedef boost::shared_ptr< ::system_monitor::CPUTemperatureStatus const> CPUTemperatureStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::system_monitor::CPUTemperatureStatus_<ContainerAllocator1> & lhs, const ::system_monitor::CPUTemperatureStatus_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.time == rhs.time &&
    lhs.cores == rhs.cores;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::system_monitor::CPUTemperatureStatus_<ContainerAllocator1> & lhs, const ::system_monitor::CPUTemperatureStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace system_monitor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1225aebb87ce815e0a8186ef49cf99cf";
  }

  static const char* value(const ::system_monitor::CPUTemperatureStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1225aebb87ce815eULL;
  static const uint64_t static_value2 = 0x0a8186ef49cf99cfULL;
};

template<class ContainerAllocator>
struct DataType< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_monitor/CPUTemperatureStatus";
  }

  static const char* value(const ::system_monitor::CPUTemperatureStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n"
"float32 time\n"
"system_monitor/CoreTemp[] cores\n"
"\n"
"================================================================================\n"
"MSG: system_monitor/CoreTemp\n"
"int8 id\n"
"#Temperature of the core in DegC\n"
"float32 temp\n"
;
  }

  static const char* value(const ::system_monitor::CPUTemperatureStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.time);
      stream.next(m.cores);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CPUTemperatureStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_monitor::CPUTemperatureStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
    s << indent << "cores[]" << std::endl;
    for (size_t i = 0; i < v.cores.size(); ++i)
    {
      s << indent << "  cores[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::system_monitor::CoreTemp_<ContainerAllocator> >::stream(s, indent + "    ", v.cores[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_MONITOR_MESSAGE_CPUTEMPERATURESTATUS_H
