// Generated by gencpp from file system_monitor/DiagnosticNET.msg
// DO NOT EDIT!


#ifndef SYSTEM_MONITOR_MESSAGE_DIAGNOSTICNET_H
#define SYSTEM_MONITOR_MESSAGE_DIAGNOSTICNET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <system_monitor/NetStatus.h>

namespace system_monitor
{
template <class ContainerAllocator>
struct DiagnosticNET_
{
  typedef DiagnosticNET_<ContainerAllocator> Type;

  DiagnosticNET_()
    : name()
    , message()
    , hardware_id()
    , status()  {
    }
  DiagnosticNET_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , message(_alloc)
    , hardware_id(_alloc)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _hardware_id_type;
  _hardware_id_type hardware_id;

   typedef  ::system_monitor::NetStatus_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::system_monitor::DiagnosticNET_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_monitor::DiagnosticNET_<ContainerAllocator> const> ConstPtr;

}; // struct DiagnosticNET_

typedef ::system_monitor::DiagnosticNET_<std::allocator<void> > DiagnosticNET;

typedef boost::shared_ptr< ::system_monitor::DiagnosticNET > DiagnosticNETPtr;
typedef boost::shared_ptr< ::system_monitor::DiagnosticNET const> DiagnosticNETConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_monitor::DiagnosticNET_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_monitor::DiagnosticNET_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::system_monitor::DiagnosticNET_<ContainerAllocator1> & lhs, const ::system_monitor::DiagnosticNET_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.message == rhs.message &&
    lhs.hardware_id == rhs.hardware_id &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::system_monitor::DiagnosticNET_<ContainerAllocator1> & lhs, const ::system_monitor::DiagnosticNET_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace system_monitor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::system_monitor::DiagnosticNET_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_monitor::DiagnosticNET_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_monitor::DiagnosticNET_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_monitor::DiagnosticNET_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_monitor::DiagnosticNET_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_monitor::DiagnosticNET_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_monitor::DiagnosticNET_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9df0f6e97d81af4d256d02e6f2a0d9b";
  }

  static const char* value(const ::system_monitor::DiagnosticNET_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9df0f6e97d81af4ULL;
  static const uint64_t static_value2 = 0xd256d02e6f2a0d9bULL;
};

template<class ContainerAllocator>
struct DataType< ::system_monitor::DiagnosticNET_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_monitor/DiagnosticNET";
  }

  static const char* value(const ::system_monitor::DiagnosticNET_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_monitor::DiagnosticNET_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string message\n"
"string hardware_id\n"
"system_monitor/NetStatus status\n"
"\n"
"================================================================================\n"
"MSG: system_monitor/NetStatus\n"
"string status\n"
"float32 time\n"
"system_monitor/Interface[] interfaces\n"
"================================================================================\n"
"MSG: system_monitor/Interface\n"
"string name\n"
"string state\n"
"#input/output speed in MB/s\n"
"float32 input\n"
"float32 output\n"
"int32 mtu\n"
"#Data received/transmitted in MB\n"
"float32 received\n"
"float32 transmitted\n"
"int32 collisions\n"
"int32 rxError\n"
"int32 txError\n"
;
  }

  static const char* value(const ::system_monitor::DiagnosticNET_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_monitor::DiagnosticNET_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.message);
      stream.next(m.hardware_id);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DiagnosticNET_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_monitor::DiagnosticNET_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_monitor::DiagnosticNET_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "hardware_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.hardware_id);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::system_monitor::NetStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_MONITOR_MESSAGE_DIAGNOSTICNET_H
