// Generated by gencpp from file system_monitor/DiagnosticCPUTemperature.msg
// DO NOT EDIT!


#ifndef SYSTEM_MONITOR_MESSAGE_DIAGNOSTICCPUTEMPERATURE_H
#define SYSTEM_MONITOR_MESSAGE_DIAGNOSTICCPUTEMPERATURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <system_monitor/CPUTemperatureStatus.h>

namespace system_monitor
{
template <class ContainerAllocator>
struct DiagnosticCPUTemperature_
{
  typedef DiagnosticCPUTemperature_<ContainerAllocator> Type;

  DiagnosticCPUTemperature_()
    : name()
    , message()
    , hardware_id()
    , status()  {
    }
  DiagnosticCPUTemperature_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , message(_alloc)
    , hardware_id(_alloc)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _hardware_id_type;
  _hardware_id_type hardware_id;

   typedef  ::system_monitor::CPUTemperatureStatus_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> const> ConstPtr;

}; // struct DiagnosticCPUTemperature_

typedef ::system_monitor::DiagnosticCPUTemperature_<std::allocator<void> > DiagnosticCPUTemperature;

typedef boost::shared_ptr< ::system_monitor::DiagnosticCPUTemperature > DiagnosticCPUTemperaturePtr;
typedef boost::shared_ptr< ::system_monitor::DiagnosticCPUTemperature const> DiagnosticCPUTemperatureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator1> & lhs, const ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.message == rhs.message &&
    lhs.hardware_id == rhs.hardware_id &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator1> & lhs, const ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace system_monitor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5cbf7e0eb0c598e791f1069d02929fe";
  }

  static const char* value(const ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5cbf7e0eb0c598eULL;
  static const uint64_t static_value2 = 0x791f1069d02929feULL;
};

template<class ContainerAllocator>
struct DataType< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_monitor/DiagnosticCPUTemperature";
  }

  static const char* value(const ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"# Possible values for message: 'OK', 'Warning','Error'\n"
"string message\n"
"string hardware_id\n"
"system_monitor/CPUTemperatureStatus status\n"
"\n"
"================================================================================\n"
"MSG: system_monitor/CPUTemperatureStatus\n"
"string status\n"
"float32 time\n"
"system_monitor/CoreTemp[] cores\n"
"\n"
"================================================================================\n"
"MSG: system_monitor/CoreTemp\n"
"int8 id\n"
"#Temperature of the core in DegC\n"
"float32 temp\n"
;
  }

  static const char* value(const ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.message);
      stream.next(m.hardware_id);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DiagnosticCPUTemperature_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_monitor::DiagnosticCPUTemperature_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "hardware_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.hardware_id);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::system_monitor::CPUTemperatureStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_MONITOR_MESSAGE_DIAGNOSTICCPUTEMPERATURE_H
