// Generated by gencpp from file system_monitor/HDDStatus.msg
// DO NOT EDIT!


#ifndef SYSTEM_MONITOR_MESSAGE_HDDSTATUS_H
#define SYSTEM_MONITOR_MESSAGE_HDDSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <system_monitor/Disk.h>

namespace system_monitor
{
template <class ContainerAllocator>
struct HDDStatus_
{
  typedef HDDStatus_<ContainerAllocator> Type;

  HDDStatus_()
    : status()
    , time(0.0)
    , space_reading()
    , disks()  {
    }
  HDDStatus_(const ContainerAllocator& _alloc)
    : status(_alloc)
    , time(0.0)
    , space_reading(_alloc)
    , disks(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;

   typedef float _time_type;
  _time_type time;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _space_reading_type;
  _space_reading_type space_reading;

   typedef std::vector< ::system_monitor::Disk_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::system_monitor::Disk_<ContainerAllocator> >::other >  _disks_type;
  _disks_type disks;





  typedef boost::shared_ptr< ::system_monitor::HDDStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_monitor::HDDStatus_<ContainerAllocator> const> ConstPtr;

}; // struct HDDStatus_

typedef ::system_monitor::HDDStatus_<std::allocator<void> > HDDStatus;

typedef boost::shared_ptr< ::system_monitor::HDDStatus > HDDStatusPtr;
typedef boost::shared_ptr< ::system_monitor::HDDStatus const> HDDStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_monitor::HDDStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_monitor::HDDStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::system_monitor::HDDStatus_<ContainerAllocator1> & lhs, const ::system_monitor::HDDStatus_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.time == rhs.time &&
    lhs.space_reading == rhs.space_reading &&
    lhs.disks == rhs.disks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::system_monitor::HDDStatus_<ContainerAllocator1> & lhs, const ::system_monitor::HDDStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace system_monitor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::system_monitor::HDDStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_monitor::HDDStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_monitor::HDDStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_monitor::HDDStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_monitor::HDDStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_monitor::HDDStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_monitor::HDDStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9464edca9fb3861e03bc3ae40d6d8bc";
  }

  static const char* value(const ::system_monitor::HDDStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9464edca9fb3861ULL;
  static const uint64_t static_value2 = 0xe03bc3ae40d6d8bcULL;
};

template<class ContainerAllocator>
struct DataType< ::system_monitor::HDDStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_monitor/HDDStatus";
  }

  static const char* value(const ::system_monitor::HDDStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_monitor::HDDStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n"
"float32 time\n"
"string space_reading\n"
"system_monitor/Disk[] disks\n"
"\n"
"================================================================================\n"
"MSG: system_monitor/Disk\n"
"int8 id\n"
"string name\n"
"string status\n"
"string mount_point\n"
"#Size of the disk in G\n"
"float32 size\n"
"float32 available\n"
"#% of total size used\n"
"float32 use\n"
;
  }

  static const char* value(const ::system_monitor::HDDStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_monitor::HDDStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.time);
      stream.next(m.space_reading);
      stream.next(m.disks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HDDStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_monitor::HDDStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_monitor::HDDStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
    s << indent << "space_reading: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.space_reading);
    s << indent << "disks[]" << std::endl;
    for (size_t i = 0; i < v.disks.size(); ++i)
    {
      s << indent << "  disks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::system_monitor::Disk_<ContainerAllocator> >::stream(s, indent + "    ", v.disks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_MONITOR_MESSAGE_HDDSTATUS_H
