(cl:defpackage robotnik_base_hw_sim-srv
  (:use )
  (:export
   "PICK"
   "<PICK-REQUEST>"
   "PICK-REQUEST"
   "<PICK-RESPONSE>"
   "PICK-RESPONSE"
   "PLACE"
   "<PLACE-REQUEST>"
   "PLACE-REQUEST"
   "<PLACE-RESPONSE>"
   "PLACE-RESPONSE"
   "SIMPLEPICK"
   "<SIMPLEPICK-REQUEST>"
   "SIMPLEPICK-REQUEST"
   "<SIMPLEPICK-RESPONSE>"
   "SIMPLEPICK-RESPONSE"
   "SIMPLEPLACE"
   "<SIMPLEPLACE-REQUEST>"
   "SIMPLEPLACE-REQUEST"
   "<SIMPLEPLACE-RESPONSE>"
   "SIMPLEPLACE-RESPONSE"
  ))

