// Auto-generated. Do not edit!

// (in-package robotnik_navigation_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let RobotnikMoveBaseFlexGoalAction = require('./RobotnikMoveBaseFlexGoalAction.js');

//-----------------------------------------------------------

class RobotnikMoveBaseFlexGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.goal = null;
    }
    else {
      if (initObj.hasOwnProperty('goal')) {
        this.goal = initObj.goal
      }
      else {
        this.goal = new RobotnikMoveBaseFlexGoalAction();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type RobotnikMoveBaseFlexGoal
    // Serialize message field [goal]
    bufferOffset = RobotnikMoveBaseFlexGoalAction.serialize(obj.goal, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type RobotnikMoveBaseFlexGoal
    let len;
    let data = new RobotnikMoveBaseFlexGoal(null);
    // Deserialize message field [goal]
    data.goal = RobotnikMoveBaseFlexGoalAction.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += RobotnikMoveBaseFlexGoalAction.getMessageSize(object.goal);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robotnik_navigation_msgs/RobotnikMoveBaseFlexGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2c383b2a93e82f0a6eee475527802b3d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    robotnik_navigation_msgs/RobotnikMoveBaseFlexGoalAction goal
    
    ================================================================================
    MSG: robotnik_navigation_msgs/RobotnikMoveBaseFlexGoalAction
    string NAVIGATION_TYPE_POINT_TO_POINT = POINT_TO_POINT
    string NAVIGATION_TYPE_END_POINT= END_POINT
    
    string GOAL_TARGET_TYPE_GPS = GPS
    string GOAL_TARGET_TYPE_CARTESIAN = CARTESIAN
    
    geometry_msgs/PoseStamped[] goal_target_pose
    string[] controller
    string[] planner
    string[] recovery_behaviors
    geometry_msgs/Pose[] goal_tolerance
    string navigation_type
    string goal_target_type
    float32 max_vel
    
    ================================================================================
    MSG: geometry_msgs/PoseStamped
    # A Pose with reference coordinate frame and timestamp
    Header header
    Pose pose
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new RobotnikMoveBaseFlexGoal(null);
    if (msg.goal !== undefined) {
      resolved.goal = RobotnikMoveBaseFlexGoalAction.Resolve(msg.goal)
    }
    else {
      resolved.goal = new RobotnikMoveBaseFlexGoalAction()
    }

    return resolved;
    }
};

module.exports = RobotnikMoveBaseFlexGoal;
