topics:
- name    : pad
  topic   : pad_teleop/cmd_vel
  timeout : 0.5
  priority: 100

#- name    : pad
#  topic   : pad_teleop/ack_cmd_vel
#  timeout : 0.5
#  priority: 100

- name    : move_base
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 50

locks:
- name    : e_stop
  topic   : robotnik_base_control/emergency_stop
  timeout : 0.0
  priority: 255
