(cl:defpackage robotnik_rms_msgs-srv
  (:use )
  (:export
   "GETMISSIONS"
   "<GETMISSIONS-REQUEST>"
   "GETMISSIONS-REQUEST"
   "<GETMISSIONS-RESPONSE>"
   "GETMISSIONS-RESPONSE"
   "IDMISSION"
   "<IDMISSION-REQUEST>"
   "IDMISSION-REQUEST"
   "<IDMISSION-RESPONSE>"
   "IDMISSION-RESPONSE"
   "MISSIONMANAGER"
   "<MISSIONMANAGER-REQUEST>"
   "MISSIONMANAGER-REQUEST"
   "<MISSIONMANAGER-RESPONSE>"
   "MISSIONMANAGER-RESPONSE"
  ))

