# Configuration Settings for C94-M8P device

debug: 1                    # Range 0-4 (0 means no debug statements will print)

save:
  mask: 3103                # Save I/O, Message, INF Message, Nav, Receiver 
                            # Manager, Antenna, and Logging Configuration
  device: 4                 # Save to EEPROM

#device: /dev/ttyACM0
device: /dev/ttyACM_GPS
frame_id: campero_gps_base_link
rate: 4                     # in Hz
nav_rate: 1                 # [# of measurement cycles], recommended 1 Hz, may 
                            # be either 5 Hz (Dual constellation) or 
                            # 8 Hz (GPS only)
dynamic_model: stationary   # max altitude 9000 m
                            # max horizontal velocity 10 m/s
                            # max vertical velocity 6 m/s
                            # max position deviation: small

fix_mode: auto              # can be 2d, 3d, both
enable_ppp: false           # Not supported by C94-M8P
dr_limit: 3                 # seconds to use deadreckoning after signal is lost

uart1:
  baudrate: 19200           # C94-M8P specific
  in: 32                    # RTCM 3
  out: 0                    # No UART out for rover

gnss:
  glonass: true             # Supported by C94-M8P
  beidou: false             # Supported by C94-M8P
  qzss: false               # Supported by C94-M8P

dgnss_mode: 3               # RTK fixed: Ambiguities are fixed wheneve
                            # possible.

inf: 
  all: true                   # Whether to display all INF messages in console

tmode3: 0                   # in the rover it is disabled

# Enable u-blox message publishers
publish:
  all: true
  aid:
    hui: false

  nav:
    posecef: false
