// Generated by gencpp from file multimap_server_msgs/LoadEnvironments.msg
// DO NOT EDIT!


#ifndef MULTIMAP_SERVER_MSGS_MESSAGE_LOADENVIRONMENTS_H
#define MULTIMAP_SERVER_MSGS_MESSAGE_LOADENVIRONMENTS_H

#include <ros/service_traits.h>


#include <multimap_server_msgs/LoadEnvironmentsRequest.h>
#include <multimap_server_msgs/LoadEnvironmentsResponse.h>


namespace multimap_server_msgs
{

struct LoadEnvironments
{

typedef LoadEnvironmentsRequest Request;
typedef LoadEnvironmentsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadEnvironments
} // namespace multimap_server_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multimap_server_msgs::LoadEnvironments > {
  static const char* value()
  {
    return "f9c07b944bb09f9a6818d9b28b6141ea";
  }

  static const char* value(const ::multimap_server_msgs::LoadEnvironments&) { return value(); }
};

template<>
struct DataType< ::multimap_server_msgs::LoadEnvironments > {
  static const char* value()
  {
    return "multimap_server_msgs/LoadEnvironments";
  }

  static const char* value(const ::multimap_server_msgs::LoadEnvironments&) { return value(); }
};


// service_traits::MD5Sum< ::multimap_server_msgs::LoadEnvironmentsRequest> should match
// service_traits::MD5Sum< ::multimap_server_msgs::LoadEnvironments >
template<>
struct MD5Sum< ::multimap_server_msgs::LoadEnvironmentsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multimap_server_msgs::LoadEnvironments >::value();
  }
  static const char* value(const ::multimap_server_msgs::LoadEnvironmentsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multimap_server_msgs::LoadEnvironmentsRequest> should match
// service_traits::DataType< ::multimap_server_msgs::LoadEnvironments >
template<>
struct DataType< ::multimap_server_msgs::LoadEnvironmentsRequest>
{
  static const char* value()
  {
    return DataType< ::multimap_server_msgs::LoadEnvironments >::value();
  }
  static const char* value(const ::multimap_server_msgs::LoadEnvironmentsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multimap_server_msgs::LoadEnvironmentsResponse> should match
// service_traits::MD5Sum< ::multimap_server_msgs::LoadEnvironments >
template<>
struct MD5Sum< ::multimap_server_msgs::LoadEnvironmentsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multimap_server_msgs::LoadEnvironments >::value();
  }
  static const char* value(const ::multimap_server_msgs::LoadEnvironmentsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multimap_server_msgs::LoadEnvironmentsResponse> should match
// service_traits::DataType< ::multimap_server_msgs::LoadEnvironments >
template<>
struct DataType< ::multimap_server_msgs::LoadEnvironmentsResponse>
{
  static const char* value()
  {
    return DataType< ::multimap_server_msgs::LoadEnvironments >::value();
  }
  static const char* value(const ::multimap_server_msgs::LoadEnvironmentsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTIMAP_SERVER_MSGS_MESSAGE_LOADENVIRONMENTS_H
