// Generated by gencpp from file multimap_server_msgs/LoadMap.msg
// DO NOT EDIT!


#ifndef MULTIMAP_SERVER_MSGS_MESSAGE_LOADMAP_H
#define MULTIMAP_SERVER_MSGS_MESSAGE_LOADMAP_H

#include <ros/service_traits.h>


#include <multimap_server_msgs/LoadMapRequest.h>
#include <multimap_server_msgs/LoadMapResponse.h>


namespace multimap_server_msgs
{

struct LoadMap
{

typedef LoadMapRequest Request;
typedef LoadMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadMap
} // namespace multimap_server_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multimap_server_msgs::LoadMap > {
  static const char* value()
  {
    return "a077cc25c08e38d71f715aaa29d797f4";
  }

  static const char* value(const ::multimap_server_msgs::LoadMap&) { return value(); }
};

template<>
struct DataType< ::multimap_server_msgs::LoadMap > {
  static const char* value()
  {
    return "multimap_server_msgs/LoadMap";
  }

  static const char* value(const ::multimap_server_msgs::LoadMap&) { return value(); }
};


// service_traits::MD5Sum< ::multimap_server_msgs::LoadMapRequest> should match
// service_traits::MD5Sum< ::multimap_server_msgs::LoadMap >
template<>
struct MD5Sum< ::multimap_server_msgs::LoadMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multimap_server_msgs::LoadMap >::value();
  }
  static const char* value(const ::multimap_server_msgs::LoadMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multimap_server_msgs::LoadMapRequest> should match
// service_traits::DataType< ::multimap_server_msgs::LoadMap >
template<>
struct DataType< ::multimap_server_msgs::LoadMapRequest>
{
  static const char* value()
  {
    return DataType< ::multimap_server_msgs::LoadMap >::value();
  }
  static const char* value(const ::multimap_server_msgs::LoadMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multimap_server_msgs::LoadMapResponse> should match
// service_traits::MD5Sum< ::multimap_server_msgs::LoadMap >
template<>
struct MD5Sum< ::multimap_server_msgs::LoadMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multimap_server_msgs::LoadMap >::value();
  }
  static const char* value(const ::multimap_server_msgs::LoadMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multimap_server_msgs::LoadMapResponse> should match
// service_traits::DataType< ::multimap_server_msgs::LoadMap >
template<>
struct DataType< ::multimap_server_msgs::LoadMapResponse>
{
  static const char* value()
  {
    return DataType< ::multimap_server_msgs::LoadMap >::value();
  }
  static const char* value(const ::multimap_server_msgs::LoadMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTIMAP_SERVER_MSGS_MESSAGE_LOADMAP_H
