// Generated by gencpp from file costmap_prohibition_layer/GetProhibitedPoints.msg
// DO NOT EDIT!


#ifndef COSTMAP_PROHIBITION_LAYER_MESSAGE_GETPROHIBITEDPOINTS_H
#define COSTMAP_PROHIBITION_LAYER_MESSAGE_GETPROHIBITEDPOINTS_H

#include <ros/service_traits.h>


#include <costmap_prohibition_layer/GetProhibitedPointsRequest.h>
#include <costmap_prohibition_layer/GetProhibitedPointsResponse.h>


namespace costmap_prohibition_layer
{

struct GetProhibitedPoints
{

typedef GetProhibitedPointsRequest Request;
typedef GetProhibitedPointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetProhibitedPoints
} // namespace costmap_prohibition_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::costmap_prohibition_layer::GetProhibitedPoints > {
  static const char* value()
  {
    return "e85019b57cf217e7d529d6333370e839";
  }

  static const char* value(const ::costmap_prohibition_layer::GetProhibitedPoints&) { return value(); }
};

template<>
struct DataType< ::costmap_prohibition_layer::GetProhibitedPoints > {
  static const char* value()
  {
    return "costmap_prohibition_layer/GetProhibitedPoints";
  }

  static const char* value(const ::costmap_prohibition_layer::GetProhibitedPoints&) { return value(); }
};


// service_traits::MD5Sum< ::costmap_prohibition_layer::GetProhibitedPointsRequest> should match
// service_traits::MD5Sum< ::costmap_prohibition_layer::GetProhibitedPoints >
template<>
struct MD5Sum< ::costmap_prohibition_layer::GetProhibitedPointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::costmap_prohibition_layer::GetProhibitedPoints >::value();
  }
  static const char* value(const ::costmap_prohibition_layer::GetProhibitedPointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::costmap_prohibition_layer::GetProhibitedPointsRequest> should match
// service_traits::DataType< ::costmap_prohibition_layer::GetProhibitedPoints >
template<>
struct DataType< ::costmap_prohibition_layer::GetProhibitedPointsRequest>
{
  static const char* value()
  {
    return DataType< ::costmap_prohibition_layer::GetProhibitedPoints >::value();
  }
  static const char* value(const ::costmap_prohibition_layer::GetProhibitedPointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::costmap_prohibition_layer::GetProhibitedPointsResponse> should match
// service_traits::MD5Sum< ::costmap_prohibition_layer::GetProhibitedPoints >
template<>
struct MD5Sum< ::costmap_prohibition_layer::GetProhibitedPointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::costmap_prohibition_layer::GetProhibitedPoints >::value();
  }
  static const char* value(const ::costmap_prohibition_layer::GetProhibitedPointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::costmap_prohibition_layer::GetProhibitedPointsResponse> should match
// service_traits::DataType< ::costmap_prohibition_layer::GetProhibitedPoints >
template<>
struct DataType< ::costmap_prohibition_layer::GetProhibitedPointsResponse>
{
  static const char* value()
  {
    return DataType< ::costmap_prohibition_layer::GetProhibitedPoints >::value();
  }
  static const char* value(const ::costmap_prohibition_layer::GetProhibitedPointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COSTMAP_PROHIBITION_LAYER_MESSAGE_GETPROHIBITEDPOINTS_H
