scan_filter_chain:
- type: laser_filters/LaserArrayFilter
  name: laser_median_filter
  params: 
    range_filter_chain:
      - name: median_5
        type: filters/MultiChannelMedianFilterFloat 
        params:
          number_of_observations: 5
          unused: 10
    intensity_filter_chain:
      - name: median_5
        type: filters/MultiChannelMedianFilterFloat 
        params:
          number_of_observations: 5
          unused: 10
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.3
    upper_threshold: 5.0
    lower_replacement_value: 0.3
    upper_replacement_value: 4.99
#- name: shadows
#  type: ScanShadowsFilter
#  params:
#    min_angle: 10
#    max_angle: 170
#    neighbors: 20
#    window: 1
#- name: dark_shadows
#  type: LaserScanIntensityFilter
#  params: 
#    lower_threshold: 100
#    upper_threshold: 10000
#    disp_histogram: 0
#- name: laser_cutoff
#  type: laser_filters/LaserScanAngularBoundsFilter
#  params:
#    lower_angle: -0.1
#    upper_angle: 0.1
