# type of navigation package/algorithm currently used
string NAVIGATION_TYPE_NONE=none
# move_base
string NAVIGATION_TYPE_1=1
# purepursuit
string NAVIGATION_TYPE_2=2
# Dock
string NAVIGATION_TYPE_3=3 

# state of the navigation node running
string NAVIGATION_STATE_INIT=init
string NAVIGATION_STATE_STANDBY=standby
string NAVIGATION_STATE_READY=ready
string NAVIGATION_STATE_EMERGENCY=emergency
string NAVIGATION_STATE_FAILURE=failure

# Navigation algorithm being used
string type

# INIT, READY, EMERGENCY, FAILURE
string state
