robotnik_navigation_msgs/RobotnikMoveBaseFlexGoalAction goal
---
robotnik_navigation_msgs/RobotnikMoveBaseFlexResultAction result
---
robotnik_navigation_msgs/RobotnikMoveBaseFlexFeedbackAction feedback

