// Generated by gencpp from file rostful_tests/WaitGoal.msg
// DO NOT EDIT!


#ifndef ROSTFUL_TESTS_MESSAGE_WAITGOAL_H
#define ROSTFUL_TESTS_MESSAGE_WAITGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rostful_tests
{
template <class ContainerAllocator>
struct WaitGoal_
{
  typedef WaitGoal_<ContainerAllocator> Type;

  WaitGoal_()
    : seconds(0)  {
    }
  WaitGoal_(const ContainerAllocator& _alloc)
    : seconds(0)  {
  (void)_alloc;
    }



   typedef int32_t _seconds_type;
  _seconds_type seconds;





  typedef boost::shared_ptr< ::rostful_tests::WaitGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rostful_tests::WaitGoal_<ContainerAllocator> const> ConstPtr;

}; // struct WaitGoal_

typedef ::rostful_tests::WaitGoal_<std::allocator<void> > WaitGoal;

typedef boost::shared_ptr< ::rostful_tests::WaitGoal > WaitGoalPtr;
typedef boost::shared_ptr< ::rostful_tests::WaitGoal const> WaitGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rostful_tests::WaitGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rostful_tests::WaitGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rostful_tests::WaitGoal_<ContainerAllocator1> & lhs, const ::rostful_tests::WaitGoal_<ContainerAllocator2> & rhs)
{
  return lhs.seconds == rhs.seconds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rostful_tests::WaitGoal_<ContainerAllocator1> & lhs, const ::rostful_tests::WaitGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rostful_tests

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rostful_tests::WaitGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostful_tests::WaitGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostful_tests::WaitGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostful_tests::WaitGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostful_tests::WaitGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostful_tests::WaitGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rostful_tests::WaitGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7185940bcec4e3e995419aeb77a0ca23";
  }

  static const char* value(const ::rostful_tests::WaitGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7185940bcec4e3e9ULL;
  static const uint64_t static_value2 = 0x95419aeb77a0ca23ULL;
};

template<class ContainerAllocator>
struct DataType< ::rostful_tests::WaitGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rostful_tests/WaitGoal";
  }

  static const char* value(const ::rostful_tests::WaitGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rostful_tests::WaitGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int32 seconds\n"
;
  }

  static const char* value(const ::rostful_tests::WaitGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rostful_tests::WaitGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seconds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaitGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rostful_tests::WaitGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rostful_tests::WaitGoal_<ContainerAllocator>& v)
  {
    s << indent << "seconds: ";
    Printer<int32_t>::stream(s, indent + "  ", v.seconds);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSTFUL_TESTS_MESSAGE_WAITGOAL_H
