global_costmap:
  global_frame: $(arg global_frame)
  robot_base_frame: $(arg base_frame)
  update_frequency: 5.0
  static_map: true
  width:  100.0
  height: 100.0

  plugins:
    - name: static_map
      type: "costmap_2d::StaticLayer"
    - name: obstacle_laser_layer_1_2
      type: "costmap_2d::ObstacleLayer"
    # - name: obstacle_laser_layer_3
    #   type: "costmap_2d::ObstacleLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"

  static_map:
      lethal_cost_threshold: 94
      static_map: true
      map_topic: map
      unknown_cost_value: 1
      trinary_costmap: false
      use_maximum: false
