#!/bin/bash
sudo apt-get remove -y ros-melodic-xmlrpc-server 
sudo apt-get remove -y ros-melodic-robot-local-control-dummy-components 
sudo apt-get remove -y ros-melodic-robot-local-control-components 
sudo apt-get remove -y ros-melodic-robot-local-control 
sudo apt-get remove -y ros-melodic-robot-local-control-procedures 
sudo apt-get remove -y ros-melodic-procedures 
sudo apt-get remove -y ros-melodic-service-shifter 
sudo apt-get remove -y ros-melodic-rosmon 
sudo apt-get remove -y ros-melodic-rqt-rosmon 
sudo apt-get remove -y ros-melodic-rosmon-core 
sudo apt-get remove -y ros-melodic-rosmon-msgs 
sudo apt-get remove -y ros-melodic-robotnik-velocity-limiter 
sudo apt-get remove -y ros-melodic-robot-local-control-msgs 
sudo apt-get remove -y ros-melodic-robotnik-signal-msgs 
sudo apt-get remove -y ros-melodic-robotnik-safety-controller 
sudo apt-get remove -y ros-melodic-robotnik-pose-filter 
sudo apt-get remove -y ros-melodic-robotnik-pad-msgs 
sudo apt-get remove -y ros-melodic-robotnik-move 
sudo apt-get remove -y ros-melodic-robotnik-locator 
sudo apt-get remove -y ros-melodic-robotnik-docker 
sudo apt-get remove -y ros-melodic-robotnik-navigation-msgs 
sudo apt-get remove -y ros-melodic-robotnik-base-hw-lib 
sudo apt-get remove -y ros-melodic-charge-manager 
sudo apt-get remove -y ros-melodic-battery-estimation 
sudo apt-get remove -y ros-melodic-rcomponent 
sudo apt-get remove -y ros-melodic-poi-manager-msgs 
sudo apt-get remove -y ros-melodic-marker-mapping 
sudo apt-get remove -y ros-melodic-robotnik-msgs 
sudo apt-get remove -y ros-melodic-robotnik-leds-msgs 
sudo apt-get remove -y ros-melodic-robot-simple-command-manager-msgs 
sudo apt-get remove -y ros-melodic-robot-local-control-test 
sudo apt-get remove -y ros-melodic-robot-local-control-bringup 
sudo apt-get remove -y ros-melodic-procedures-test-msgs 
sudo apt-get remove -y ros-melodic-procedures-msgs 
sudo apt-get remove -y ros-melodic-multimap-server-msgs 
sudo apt-get remove -y ros-melodic-interactive-marker-proxy 
sudo apt-get remove -y ros-melodic-image-filter 
