// Generated by gencpp from file poi_manager_msgs/AddPOI.msg
// DO NOT EDIT!


#ifndef POI_MANAGER_MSGS_MESSAGE_ADDPOI_H
#define POI_MANAGER_MSGS_MESSAGE_ADDPOI_H

#include <ros/service_traits.h>


#include <poi_manager_msgs/AddPOIRequest.h>
#include <poi_manager_msgs/AddPOIResponse.h>


namespace poi_manager_msgs
{

struct AddPOI
{

typedef AddPOIRequest Request;
typedef AddPOIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddPOI
} // namespace poi_manager_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::poi_manager_msgs::AddPOI > {
  static const char* value()
  {
    return "31c6c5ebe956d1a071c7fa7bf0f79398";
  }

  static const char* value(const ::poi_manager_msgs::AddPOI&) { return value(); }
};

template<>
struct DataType< ::poi_manager_msgs::AddPOI > {
  static const char* value()
  {
    return "poi_manager_msgs/AddPOI";
  }

  static const char* value(const ::poi_manager_msgs::AddPOI&) { return value(); }
};


// service_traits::MD5Sum< ::poi_manager_msgs::AddPOIRequest> should match
// service_traits::MD5Sum< ::poi_manager_msgs::AddPOI >
template<>
struct MD5Sum< ::poi_manager_msgs::AddPOIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::poi_manager_msgs::AddPOI >::value();
  }
  static const char* value(const ::poi_manager_msgs::AddPOIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::poi_manager_msgs::AddPOIRequest> should match
// service_traits::DataType< ::poi_manager_msgs::AddPOI >
template<>
struct DataType< ::poi_manager_msgs::AddPOIRequest>
{
  static const char* value()
  {
    return DataType< ::poi_manager_msgs::AddPOI >::value();
  }
  static const char* value(const ::poi_manager_msgs::AddPOIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::poi_manager_msgs::AddPOIResponse> should match
// service_traits::MD5Sum< ::poi_manager_msgs::AddPOI >
template<>
struct MD5Sum< ::poi_manager_msgs::AddPOIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::poi_manager_msgs::AddPOI >::value();
  }
  static const char* value(const ::poi_manager_msgs::AddPOIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::poi_manager_msgs::AddPOIResponse> should match
// service_traits::DataType< ::poi_manager_msgs::AddPOI >
template<>
struct DataType< ::poi_manager_msgs::AddPOIResponse>
{
  static const char* value()
  {
    return DataType< ::poi_manager_msgs::AddPOI >::value();
  }
  static const char* value(const ::poi_manager_msgs::AddPOIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POI_MANAGER_MSGS_MESSAGE_ADDPOI_H
