// Generated by gencpp from file poi_manager_msgs/DeleteEnvironmentRequest.msg
// DO NOT EDIT!


#ifndef POI_MANAGER_MSGS_MESSAGE_DELETEENVIRONMENTREQUEST_H
#define POI_MANAGER_MSGS_MESSAGE_DELETEENVIRONMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poi_manager_msgs
{
template <class ContainerAllocator>
struct DeleteEnvironmentRequest_
{
  typedef DeleteEnvironmentRequest_<ContainerAllocator> Type;

  DeleteEnvironmentRequest_()
    : environment()  {
    }
  DeleteEnvironmentRequest_(const ContainerAllocator& _alloc)
    : environment(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _environment_type;
  _environment_type environment;





  typedef boost::shared_ptr< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DeleteEnvironmentRequest_

typedef ::poi_manager_msgs::DeleteEnvironmentRequest_<std::allocator<void> > DeleteEnvironmentRequest;

typedef boost::shared_ptr< ::poi_manager_msgs::DeleteEnvironmentRequest > DeleteEnvironmentRequestPtr;
typedef boost::shared_ptr< ::poi_manager_msgs::DeleteEnvironmentRequest const> DeleteEnvironmentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator1> & lhs, const ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator2> & rhs)
{
  return lhs.environment == rhs.environment;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator1> & lhs, const ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace poi_manager_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70802a554778fff9dda739539d9b31b7";
  }

  static const char* value(const ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70802a554778fff9ULL;
  static const uint64_t static_value2 = 0xdda739539d9b31b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_manager_msgs/DeleteEnvironmentRequest";
  }

  static const char* value(const ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string environment\n"
;
  }

  static const char* value(const ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.environment);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeleteEnvironmentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_manager_msgs::DeleteEnvironmentRequest_<ContainerAllocator>& v)
  {
    s << indent << "environment: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.environment);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_MANAGER_MSGS_MESSAGE_DELETEENVIRONMENTREQUEST_H
