// Generated by gencpp from file poi_manager_msgs/GetPOIResponse.msg
// DO NOT EDIT!


#ifndef POI_MANAGER_MSGS_MESSAGE_GETPOIRESPONSE_H
#define POI_MANAGER_MSGS_MESSAGE_GETPOIRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <poi_manager_msgs/LabeledPose.h>

namespace poi_manager_msgs
{
template <class ContainerAllocator>
struct GetPOIResponse_
{
  typedef GetPOIResponse_<ContainerAllocator> Type;

  GetPOIResponse_()
    : success(false)
    , message()
    , p()  {
    }
  GetPOIResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , p(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef  ::poi_manager_msgs::LabeledPose_<ContainerAllocator>  _p_type;
  _p_type p;





  typedef boost::shared_ptr< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPOIResponse_

typedef ::poi_manager_msgs::GetPOIResponse_<std::allocator<void> > GetPOIResponse;

typedef boost::shared_ptr< ::poi_manager_msgs::GetPOIResponse > GetPOIResponsePtr;
typedef boost::shared_ptr< ::poi_manager_msgs::GetPOIResponse const> GetPOIResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator1> & lhs, const ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.p == rhs.p;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator1> & lhs, const ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace poi_manager_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02b7693c2cf785bfb906626d74643da9";
  }

  static const char* value(const ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02b7693c2cf785bfULL;
  static const uint64_t static_value2 = 0xb906626d74643da9ULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_manager_msgs/GetPOIResponse";
  }

  static const char* value(const ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"poi_manager_msgs/LabeledPose p\n"
"\n"
"================================================================================\n"
"MSG: poi_manager_msgs/LabeledPose\n"
"string name\n"
"string environment\n"
"string params\n"
"string frame_id\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPOIResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_manager_msgs::GetPOIResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "p: ";
    s << std::endl;
    Printer< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> >::stream(s, indent + "  ", v.p);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_MANAGER_MSGS_MESSAGE_GETPOIRESPONSE_H
