// Generated by gencpp from file poi_manager_msgs/LabeledPose.msg
// DO NOT EDIT!


#ifndef POI_MANAGER_MSGS_MESSAGE_LABELEDPOSE_H
#define POI_MANAGER_MSGS_MESSAGE_LABELEDPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace poi_manager_msgs
{
template <class ContainerAllocator>
struct LabeledPose_
{
  typedef LabeledPose_<ContainerAllocator> Type;

  LabeledPose_()
    : name()
    , environment()
    , params()
    , frame_id()
    , pose()  {
    }
  LabeledPose_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , environment(_alloc)
    , params(_alloc)
    , frame_id(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _environment_type;
  _environment_type environment;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _params_type;
  _params_type params;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> const> ConstPtr;

}; // struct LabeledPose_

typedef ::poi_manager_msgs::LabeledPose_<std::allocator<void> > LabeledPose;

typedef boost::shared_ptr< ::poi_manager_msgs::LabeledPose > LabeledPosePtr;
typedef boost::shared_ptr< ::poi_manager_msgs::LabeledPose const> LabeledPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_manager_msgs::LabeledPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::poi_manager_msgs::LabeledPose_<ContainerAllocator1> & lhs, const ::poi_manager_msgs::LabeledPose_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.environment == rhs.environment &&
    lhs.params == rhs.params &&
    lhs.frame_id == rhs.frame_id &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::poi_manager_msgs::LabeledPose_<ContainerAllocator1> & lhs, const ::poi_manager_msgs::LabeledPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace poi_manager_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be4e6a8e496916cefd9c45caa2ab4459";
  }

  static const char* value(const ::poi_manager_msgs::LabeledPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe4e6a8e496916ceULL;
  static const uint64_t static_value2 = 0xfd9c45caa2ab4459ULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_manager_msgs/LabeledPose";
  }

  static const char* value(const ::poi_manager_msgs::LabeledPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string environment\n"
"string params\n"
"string frame_id\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::poi_manager_msgs::LabeledPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.environment);
      stream.next(m.params);
      stream.next(m.frame_id);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LabeledPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_manager_msgs::LabeledPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_manager_msgs::LabeledPose_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "environment: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.environment);
    s << indent << "params: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.params);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_MANAGER_MSGS_MESSAGE_LABELEDPOSE_H
