# rbares: configuration for real leds

signals:

  - id: "forward"
    enabled: false
    led_label: ["front_leds"]
    mode: "blink"
    color: [0, 20, 0, 0]
    ms_on: 500
    ms_off: 500

  - id: "backward"
    enabled: false
    led_label:  ["all_leds"]
    mode: "blink"
    color: [0, 20, 0, 0]
    ms_on: 500
    ms_off: 500



  - id: "turn_right"
    enabled: false
    led_label: ["right_leds", "left_leds", "front_leds"]
    mode: "shift"
    color: [0, 20, 0, 0]
    direction: "left"
    led_increment: 1
    speed: 2000


  - id: "turn_left"
    enabled: false
    led_label: ["right_leds", "left_leds", "front_leds"]
    mode: "shift"
    color: [0, 20, 0, 0]
    direction: "right"
    led_increment: 1
    speed: 2000


  - id: "turn_right_inverse"
    enabled: false
    led_label: ["right_leds", "left_leds", "front_leds"]
    mode: "shift"
    color: [0, 20, 0, 0]
    direction: "left"
    led_increment: 1
    speed: 2000


  - id: "turn_left_inverse"
    enabled: false
    led_label: ["right_leds", "left_leds", "front_leds"]
    mode: "shift"
    color: [0, 20, 0, 0]
    direction: "right"
    led_increment: 1
    speed: 2000


  - id: "stop_robot"
    enabled: false
    led_label: ["all_leds"]
    mode: "paint"
    color: [0, 20, 0, 0]

  
  - id: "emergency_stop"
    enabled: false
    led_label: ["all_leds"]
    mode: "paint"
    color: [20, 0, 0, 0]




