(cl:in-package robotnik_leds_msgs-srv)
(cl:export '(PASSWORD-VAL
          PASSWORD
          STATE-VAL
          STATE
          MODE-VAL
          MODE
          COLOR_R-VAL
          COLOR_R
          COLOR_G-VAL
          COLOR_G
          COLOR_B-VAL
          COLOR_B
          COLOR_W-VAL
          COLOR_W
          START_LED-VAL
          START_LED
          END_LED-VAL
          END_LED
          MS_ON-VAL
          MS_ON
          MS_OFF-VAL
          MS_OFF
          DIRECTION-VAL
          DIRECTION
          SPEED-VAL
          SPEED
          MESSAGE-VAL
          MESSAGE
))