(cl:defpackage robotnik_leds_msgs-srv
  (:use )
  (:export
   "LEDCONFIG"
   "<LEDCONFIG-REQUEST>"
   "LEDCONFIG-REQUEST"
   "<LEDCONFIG-RESPONSE>"
   "LEDCONFIG-RESPONSE"
   "LEDEFFECTS"
   "<LEDEFFECTS-REQUEST>"
   "LEDEFFECTS-REQUEST"
   "<LEDEFFECTS-RESPONSE>"
   "LEDEFFECTS-RESPONSE"
   "LEDRESET"
   "<LEDRESET-REQUEST>"
   "LEDRESET-REQUEST"
   "<LEDRESET-RESPONSE>"
   "LEDRESET-RESPONSE"
  ))

