(cl:in-package robotnik_leds_msgs-srv)
(cl:export '(ID-VAL
          ID
          MODE-VAL
          MODE
          CHANNEL-VAL
          CHANNEL
          TYPE-VAL
          TYPE
          COLOR_R-VAL
          COLOR_R
          COLOR_G-VAL
          COLOR_G
          COLOR_B-VAL
          COLOR_B
          COLOR_W-VAL
          COLOR_W
          START_LED-VAL
          START_LED
          END_LED-VAL
          END_LED
          MS_ON-VAL
          MS_ON
          MS_OFF-VAL
          MS_OFF
          FADE_IN-VAL
          FADE_IN
          FADE_OUT-VAL
          FADE_OUT
          BACKGROUND_R-VAL
          BACKGROUND_R
          BACKGROUND_G-VAL
          BACKGROUND_G
          BACKGROUND_B-VAL
          BACKGROUND_B
          BACKGROUND_W-VAL
          BACKGROUND_W
          DIRECTION-VAL
          DIRECTION
          SPEED-VAL
          SPEED
          SLEEP-VAL
          SLEEP
          LED_INCREMENT-VAL
          LED_INCREMENT
          LAYER-VAL
          LAYER
          ENABLED-VAL
          ENABLED
          STATE-VAL
          STATE
))