// Generated by gencpp from file robotnik_leds_msgs/LedConfigResponse.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_LEDS_MSGS_MESSAGE_LEDCONFIGRESPONSE_H
#define ROBOTNIK_LEDS_MSGS_MESSAGE_LEDCONFIGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotnik_leds_msgs
{
template <class ContainerAllocator>
struct LedConfigResponse_
{
  typedef LedConfigResponse_<ContainerAllocator> Type;

  LedConfigResponse_()
    : message()  {
    }
  LedConfigResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LedConfigResponse_

typedef ::robotnik_leds_msgs::LedConfigResponse_<std::allocator<void> > LedConfigResponse;

typedef boost::shared_ptr< ::robotnik_leds_msgs::LedConfigResponse > LedConfigResponsePtr;
typedef boost::shared_ptr< ::robotnik_leds_msgs::LedConfigResponse const> LedConfigResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator1> & lhs, const ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator1> & lhs, const ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotnik_leds_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_leds_msgs/LedConfigResponse";
  }

  static const char* value(const ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"\n"
;
  }

  static const char* value(const ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LedConfigResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_leds_msgs::LedConfigResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_LEDS_MSGS_MESSAGE_LEDCONFIGRESPONSE_H
