(cl:defpackage costmap_prohibition_layer-srv
  (:use )
  (:export
   "ADDPROHIBITEDPOINTS"
   "<ADDPROHIBITEDPOINTS-REQUEST>"
   "ADDPROHIBITEDPOINTS-REQUEST"
   "<ADDPROHIBITEDPOINTS-RESPONSE>"
   "ADDPROHIBITEDPOINTS-RESPONSE"
   "CLEARPROHIBITEDPOINTS"
   "<CLEARPROHIBITEDPOINTS-REQUEST>"
   "CLEARPROHIBITEDPOINTS-REQUEST"
   "<CLEARPROHIBITEDPOINTS-RESPONSE>"
   "CLEARPROHIBITEDPOINTS-RESPONSE"
   "GETPROHIBITEDPOINTS"
   "<GETPROHIBITEDPOINTS-REQUEST>"
   "GETPROHIBITEDPOINTS-REQUEST"
   "<GETPROHIBITEDPOINTS-RESPONSE>"
   "GETPROHIBITEDPOINTS-RESPONSE"
   "SETPROHIBITEDPOINTS"
   "<SETPROHIBITEDPOINTS-REQUEST>"
   "SETPROHIBITEDPOINTS-REQUEST"
   "<SETPROHIBITEDPOINTS-RESPONSE>"
   "SETPROHIBITEDPOINTS-RESPONSE"
  ))

