; Auto-generated. Do not edit!


(cl:in-package robot_simple_command_manager_msgs-msg)


;//! \htmlinclude RobotSimpleCommandFeedback.msg.html

(cl:defclass <RobotSimpleCommandFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type robot_simple_command_manager_msgs-msg:CommandStringFeedback
    :initform (cl:make-instance 'robot_simple_command_manager_msgs-msg:CommandStringFeedback)))
)

(cl:defclass RobotSimpleCommandFeedback (<RobotSimpleCommandFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RobotSimpleCommandFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RobotSimpleCommandFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_simple_command_manager_msgs-msg:<RobotSimpleCommandFeedback> is deprecated: use robot_simple_command_manager_msgs-msg:RobotSimpleCommandFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <RobotSimpleCommandFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_simple_command_manager_msgs-msg:feedback-val is deprecated.  Use robot_simple_command_manager_msgs-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RobotSimpleCommandFeedback>) ostream)
  "Serializes a message object of type '<RobotSimpleCommandFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'feedback) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RobotSimpleCommandFeedback>) istream)
  "Deserializes a message object of type '<RobotSimpleCommandFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'feedback) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RobotSimpleCommandFeedback>)))
  "Returns string type for a message object of type '<RobotSimpleCommandFeedback>"
  "robot_simple_command_manager_msgs/RobotSimpleCommandFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RobotSimpleCommandFeedback)))
  "Returns string type for a message object of type 'RobotSimpleCommandFeedback"
  "robot_simple_command_manager_msgs/RobotSimpleCommandFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RobotSimpleCommandFeedback>)))
  "Returns md5sum for a message object of type '<RobotSimpleCommandFeedback>"
  "015daefc8dc068e08825df2bf655e8de")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RobotSimpleCommandFeedback)))
  "Returns md5sum for a message object of type 'RobotSimpleCommandFeedback"
  "015daefc8dc068e08825df2bf655e8de")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RobotSimpleCommandFeedback>)))
  "Returns full string definition for message of type '<RobotSimpleCommandFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%robot_simple_command_manager_msgs/CommandStringFeedback feedback~%~%~%================================================================================~%MSG: robot_simple_command_manager_msgs/CommandStringFeedback~%string command~%string status~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RobotSimpleCommandFeedback)))
  "Returns full string definition for message of type 'RobotSimpleCommandFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%robot_simple_command_manager_msgs/CommandStringFeedback feedback~%~%~%================================================================================~%MSG: robot_simple_command_manager_msgs/CommandStringFeedback~%string command~%string status~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RobotSimpleCommandFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RobotSimpleCommandFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RobotSimpleCommandFeedback
    (cl:cons ':feedback (feedback msg))
))
