// Generated by gencpp from file robotnik_base_hw_sim/PickRequest.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_BASE_HW_SIM_MESSAGE_PICKREQUEST_H
#define ROBOTNIK_BASE_HW_SIM_MESSAGE_PICKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace robotnik_base_hw_sim
{
template <class ContainerAllocator>
struct PickRequest_
{
  typedef PickRequest_<ContainerAllocator> Type;

  PickRequest_()
    : object_model()
    , object_link()
    , robot_model()
    , robot_link()
    , pose()  {
    }
  PickRequest_(const ContainerAllocator& _alloc)
    : object_model(_alloc)
    , object_link(_alloc)
    , robot_model(_alloc)
    , robot_link(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_model_type;
  _object_model_type object_model;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_link_type;
  _object_link_type object_link;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_model_type;
  _robot_model_type robot_model;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_link_type;
  _robot_link_type robot_link;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PickRequest_

typedef ::robotnik_base_hw_sim::PickRequest_<std::allocator<void> > PickRequest;

typedef boost::shared_ptr< ::robotnik_base_hw_sim::PickRequest > PickRequestPtr;
typedef boost::shared_ptr< ::robotnik_base_hw_sim::PickRequest const> PickRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator1> & lhs, const ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator2> & rhs)
{
  return lhs.object_model == rhs.object_model &&
    lhs.object_link == rhs.object_link &&
    lhs.robot_model == rhs.robot_model &&
    lhs.robot_link == rhs.robot_link &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator1> & lhs, const ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotnik_base_hw_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ce29537d89f0f0f0ab7afe25c8e28e1";
  }

  static const char* value(const ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ce29537d89f0f0fULL;
  static const uint64_t static_value2 = 0x0ab7afe25c8e28e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_base_hw_sim/PickRequest";
  }

  static const char* value(const ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# attach object link into robot link\n"
"# Links and models are refered to Gazebo\n"
"string object_model\n"
"string object_link\n"
"string robot_model\n"
"string robot_link\n"
"# pose related to the robot link\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_model);
      stream.next(m.object_link);
      stream.next(m.robot_model);
      stream.next(m.robot_link);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_base_hw_sim::PickRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_model: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_model);
    s << indent << "object_link: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_link);
    s << indent << "robot_model: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_model);
    s << indent << "robot_link: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_link);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_BASE_HW_SIM_MESSAGE_PICKREQUEST_H
