// Generated by gencpp from file robotnik_base_hw_sim/Place.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_BASE_HW_SIM_MESSAGE_PLACE_H
#define ROBOTNIK_BASE_HW_SIM_MESSAGE_PLACE_H

#include <ros/service_traits.h>


#include <robotnik_base_hw_sim/PlaceRequest.h>
#include <robotnik_base_hw_sim/PlaceResponse.h>


namespace robotnik_base_hw_sim
{

struct Place
{

typedef PlaceRequest Request;
typedef PlaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Place
} // namespace robotnik_base_hw_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_base_hw_sim::Place > {
  static const char* value()
  {
    return "07bbfe2a52b1b081057b9ea660d0c474";
  }

  static const char* value(const ::robotnik_base_hw_sim::Place&) { return value(); }
};

template<>
struct DataType< ::robotnik_base_hw_sim::Place > {
  static const char* value()
  {
    return "robotnik_base_hw_sim/Place";
  }

  static const char* value(const ::robotnik_base_hw_sim::Place&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_base_hw_sim::PlaceRequest> should match
// service_traits::MD5Sum< ::robotnik_base_hw_sim::Place >
template<>
struct MD5Sum< ::robotnik_base_hw_sim::PlaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_base_hw_sim::Place >::value();
  }
  static const char* value(const ::robotnik_base_hw_sim::PlaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_base_hw_sim::PlaceRequest> should match
// service_traits::DataType< ::robotnik_base_hw_sim::Place >
template<>
struct DataType< ::robotnik_base_hw_sim::PlaceRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_base_hw_sim::Place >::value();
  }
  static const char* value(const ::robotnik_base_hw_sim::PlaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_base_hw_sim::PlaceResponse> should match
// service_traits::MD5Sum< ::robotnik_base_hw_sim::Place >
template<>
struct MD5Sum< ::robotnik_base_hw_sim::PlaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_base_hw_sim::Place >::value();
  }
  static const char* value(const ::robotnik_base_hw_sim::PlaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_base_hw_sim::PlaceResponse> should match
// service_traits::DataType< ::robotnik_base_hw_sim::Place >
template<>
struct DataType< ::robotnik_base_hw_sim::PlaceResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_base_hw_sim::Place >::value();
  }
  static const char* value(const ::robotnik_base_hw_sim::PlaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_BASE_HW_SIM_MESSAGE_PLACE_H
